### ISSUE TITLE
Ride Any Unit As Your Mount Option Doesn't Work For Some Expanded Content Companions (posted per CascadingDragon's request)

### ISSUE THREAD

**Issue by Vaeliorin** [cabarius/ToyBox#1033]
### Description of the bug

With Ride Any Unit As Your Mount turned on, there are creatures from Expanded Content that can't be mounted due to them having an Unmountable buff.

### Steps To Reproduce

Choose Treesinger Druid, pick Treant Companion
Level up until Treant becomes Large
Try to mount Treant 

### Expected Behavior

Expected to be able to mount the treant.

### Toybox Version

1.5.6

### Operating System

Windows 10

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.1.5r

### Anything else?

Posted at the request of CascadingDragon from Wrath modding Discord

**Comment by CasDragon** [comment]
So while I don't remember asking you to make the bug report, I can confirm this is still an issue. 
ADDB released a preview version in Discord a few hours back that did not fix the issue.
