### ISSUE TITLE
Exclude swarm when "all" dialog options is on

### ISSUE THREAD

**Issue by edvin76** [cabarius/ToyBox#1052]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

hi, do you think you guys could add an option to the "show all mythic dialog options" that the dialogs wouldn't show the swarm option? it is so off putting to see in almost every dialog that "do you wanna eat her?", i hate the swarm path and I actually stopped playing the game it became such an issue during the last act, 

you have an option to eat your dialog partner in almost every dialog.... seriously? super sad

**Comment by CasDragon** [comment]
Unlikely to be added. Simply ignore the dialog, or turn off the option. 
However, if you are willing to do it yourself, we would gladly accept a PR on it.
