### ISSUE TITLE
1hp bug back

### ISSUE THREAD

**Issue by RoivasO** [cabarius/ToyBox#1054]
### Description of the bug

1hp and 0 hit dice bug back after changing player character's religion (adding Urgathoa removing Pharasma).  Have tried disabling mod and reverting back to save 6 hours prior and bug still in place. 

Updating Toybox, reverting to old save, disabling Toybox, and verifying game install have all failed to correct issue.  

Appears to have permanently altered game. 

### Steps To Reproduce

changing player character's religion (adding Urgathoa removing Pharasma) and enter any combat zone

### Log Files

[GameLogPrev.txt](https://github.com/cabarius/ToyBox/files/13257199/GameLogPrev.txt)

### Save File

[saves.zip](https://github.com/cabarius/ToyBox/files/13257198/saves.zip)

### Settings

[general_settings.json](https://github.com/cabarius/ToyBox/files/13257212/general_settings.json)

### Toybox Version

originally 1.5.5 then updated to 1.5.7 and bug remianed

### Operating System

Windows

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.1.5r

**Comment by CasDragon** [comment]
Load a save from before the update which caused the 1 hp bug, as the bug effects the save permanently.

**Comment by RoivasO** [comment]
I'm not sure what patch that would be. I don't think there's been a patch since I started so does that mean the whole playthough can't be recovered?

**Comment by RoivasO** [comment]
So, doing a fresh install of the game and a fresh install of Toybox, then loading from a save prior to attempting to make the change via Toybox seems to have fixed the problem. 

Thanks all!
