### ISSUE TITLE
Inevitable Excess Breaks Gestalt

### ISSUE THREAD

**Issue by DanZinagri** [cabarius/ToyBox#1055]
### Description of the bug

So for the main character this works "fine", the DLC is prone to being buggy in general but you can usually get through the level up process mostly fine.

When attempting to respec other party members suddenly the whole thing goes sideways. Hilor, Toybox, and the Respec Mod (even trying to force them into mercenary). 

This also breaks it for the characters loading other saves; but the moment you reboot the game and either load a non-inevitable excess save or start a new one, whole process works fine.

It either won't apply the 2nd class you checkbox, or once selecting it, and swapping it you'll end up with something like this where it'll show the wrong archetype on the main class, with the 2nd class set to 0 level. I attempted to respec the 1st level, then gestalt the remainder (as that sometimes works), but instead it just won't level up the 2nd class, but it'll keep reporting that it put more levels in it (like 3 levels of cavalier being shown despite it not actually gotten a new feature since 1).

### Steps To Reproduce

1. Start a inevitable excess run. Finish character creation.
2. Get your party
3. Attempt to respec through either hilor, Toybox, or respec mod.
4. Attempt to gestalt.
5. Exit/reload game and attempt same steps on non-inevitable excess game and confirm it still works there.

### Expected Behavior

Gestalt wouldn't be broken for specifically this DLC.

### Screenshots

![image](https://github.com/cabarius/ToyBox/assets/98767002/9e7bde04-af5f-49e0-b0d9-a172df86a6fd)

### Toybox Version

1.5.8a

### Operating System

Linux(Proton), (also attempted on Windows).

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.2.1a

**Comment by CasDragon** [comment]
Can't replicate. 
See the [Gestalt Guide](https://github.com/cabarius/ToyBox/wiki/Gestalt-Guide) to make sure you are doing it the correct way.
