### ISSUE TITLE
Selecting "Duel Swords" category in "Weapons" tab makes Toybox crashed. 

### ISSUE THREAD

**Issue by BlackburnZZ** [cabarius/ToyBox#1061]
### Description of the bug

 As title says - Selecting "Duel Swords" category in "Weapons" tab makes Toybox crashed. 

### Steps To Reproduce

Go to "Weapons" tab
Select "Duel Swords" category
After that ToyBox crash with errors (but not the game, i mean you can continue to play)

### Log Files

[Player.log](https://github.com/cabarius/ToyBox/files/13527899/Player.log)
[GameLogFull.txt](https://github.com/cabarius/ToyBox/files/13527901/GameLogFull.txt)

### Screenshots

![Error](https://github.com/cabarius/ToyBox/assets/94981413/c9e19a61-8d41-458b-ae93-d15dfb36b75a)

### Toybox Version

1.5.8

### Operating System

Windows 10 x64

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.2.1a

**Comment by CasDragon** [comment]
Are you on the main menu when you are getting that error? Because it looks like that, and Toybox has limited functionality on the main menu. While we should probably make the "Enhancement" tab just not load on Main Menu (or we might have already done that), if that errors from the main menu, it's not really an issue

**Comment by BlackburnZZ** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/62178123/287329301-d2f43caa-f0fa-4337-9a0b-f1a867db9ff5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDk4NzcsIm5iZiI6MTcwMTQ0OTU3NywicGF0aCI6Ii82MjE3ODEyMy8yODczMjkzMDEtZDJmNDNjYWEtZjBmYS00MzM3LTlhMGItZjFhODY3ZGI5ZmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE2NTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYmI4ZTA0MTUyMTE0MmEwODI5MjI1Y2ZjNmUwMWI0ZDQ1ZTdjOWRlZWYyMzYwZmFjNWZjMGU2MGY3MGYwM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KbFirnsa41iI3uNRubcMRNrMIUNH5H26djJDv3FBXQE)

If I understand it correctly, then I need to add this missing part? Where can I find this file so I can fix this?
Sorry, this is just a little new to me.
And thank you

**Comment by BlackburnZZ** [comment]
Update - Also the same problem with "LightMace" category.

**Comment by BlackburnZZ** [comment]
> > > ![grafik](https://private-user-images.githubusercontent.com/62178123/287329301-d2f43caa-f0fa-4337-9a0b-f1a867db9ff5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDk4NzcsIm5iZiI6MTcwMTQ0OTU3NywicGF0aCI6Ii82MjE3ODEyMy8yODczMjkzMDEtZDJmNDNjYWEtZjBmYS00MzM3LTlhMGItZjFhODY3ZGI5ZmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE2NTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYmI4ZTA0MTUyMTE0MmEwODI5MjI1Y2ZjNmUwMWI0ZDQ1ZTdjOWRlZWYyMzYwZmFjNWZjMGU2MGY3MGYwM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KbFirnsa41iI3uNRubcMRNrMIUNH5H26djJDv3FBXQE)
> > 
> > 
> > If I understand it correctly, then I need to add this missing part? Where can I find this file so I can fix this?
> > Sorry, this is just a little new to me.
> > And thank you
> 
> That was a screenshot of the part of the code where the issue is. It's for either future me or anyone else who'll tackle the problem.
> 
> Though if I understand correctly it might be calling the Rating method on a null BlueprintEnchantment which is weird. Nullcheck + return 0 should fix?

Because I understand absolutely nothing about this, I'll just wait for a future fix :). Thank you anyway for your answers!

**Comment by BlackburnZZ** [comment]
> I can't reproduce the issue. Be sure to verify your game files. Just in case this version should've additional checks against your issue: [0ToyBox0-Wrath.zip](https://github.com/cabarius/ToyBox/files/13547073/0ToyBox0-Wrath.zip)

I did have one corrupted file while verifying the game, but it still didn't solve the problem.
But your fix worked! Now both categories are loaded and weapons can be added without problems!
Thank you very much!

**Comment by BlackburnZZ** [comment]
![1](https://github.com/cabarius/ToyBox/assets/94981413/ebc3be65-66ba-4dfb-9466-974563daba96)
Another update - now i can't open "Party" tab. 
In previous version (1.5.8a) it worked, but with current fix (1.5.8b) it's not.
Sorry about that, i don't know why it's happening. I've never had any problems with ToyBox before.

**Comment by BlackburnZZ** [comment]
![1](https://github.com/cabarius/ToyBox/assets/94981413/586bb622-cc6a-4ad6-980b-9fe565cb1eae)
[Player.log](https://github.com/cabarius/ToyBox/files/13554504/Player.log)
[GameLogFull.txt](https://github.com/cabarius/ToyBox/files/13554505/GameLogFull.txt)
Update again - now i can't open "Party" tab...
This worked in the previous version (1.5.8a) and with current fix (1.5.8b) it's not.
I apologize for the inconvenience, I don't understand why this is happening. Previously, there were no such problems at all.

**Comment by BlackburnZZ** [comment]
> If you can send over a save I could try and see if the issue is related to that one of these days.
Sure! 
[Manual_780_save_with_ToyBox_1_5_8b___.zip](https://github.com/cabarius/ToyBox/files/13554978/Manual_780_save_with_ToyBox_1_5_8b___.zip)
