### ISSUE TITLE
PartyEditor.OnGUI is throwing NullReferenceException

### ISSUE THREAD

**Issue by xADDBx** [cabarius/ToyBox#1062]
![1](https://github.com/cabarius/ToyBox/assets/94981413/586bb622-cc6a-4ad6-980b-9fe565cb1eae)
[Player.log](https://github.com/cabarius/ToyBox/files/13554504/Player.log)
[GameLogFull.txt](https://github.com/cabarius/ToyBox/files/13554505/GameLogFull.txt)
Update again - now i can't open "Party" tab... (on loaded save. In the main menu i can open it)
This worked in the previous version (1.5.8a) and with current fix (1.5.8b) it's not.
I apologize for the inconvenience, I don't understand why this is happening. Previously, there were no such problems at all.

_Originally posted by @BlackburnZZ in https://github.com/cabarius/ToyBox/issues/1061#issuecomment-1839916087_

**Comment by BlackburnZZ** [comment]
> @BlackburnZZ does the following version still cause said issue? I was first able to reproduce your issue, after recompiling once, I haven't been able to trigger the exception with that version: [0ToyBox0-Wrath.zip](https://github.com/cabarius/ToyBox/files/13594339/0ToyBox0-Wrath.zip)

Hello! No, now it's work like a charm! No errors or crashes this time! And problematic weapons categories are working too!
Thank you again for your help and patience!
