### ISSUE TITLE
Religion DC for movespeed buff increasing indefinitely (causing infinite black screen)

### ISSUE THREAD

**Issue by xADDBx** [cabarius/ToyBox#1072]
### Description of the bug

Not sure if that's a toybox only bug, but someone had a similar issue a week or 2 ago where the religion DC check to (i think) determine the length of the movespeed buff after rest would be attempted until fail by increasing the dc by 5 each time. But because they couldn't fail the check, it increased something like 70 000 times and they were stuck in a infinite black screen because it wouldn't stop going up (Source: https://discord.com/channels/645948717400064030/815735034514112512/1189256931957817384)

### Steps To Reproduce

Blup

### Toybox Version

1.5.9

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

**Comment by CasDragon** [comment]
Believe this was fixed in 1.5.10a?
