### ISSUE TITLE
Maybe Search and Pick Crash

### ISSUE THREAD

**Issue by xADDBx** [cabarius/ToyBox#1073]
### Description of the bug

https://cdn.discordapp.com/attachments/1188240709401194496/1188241273589604352/IMG_20231223_125725653_HDR.jpg?ex=6599ceec&is=658759ec&hm=1bccd5a8d06877c54705e7b7d3337fa4a5e35a3aba4c9284787ce0d8782092e0&
Do you know what is causing this crash when using search and pick?  
Wrath Yes  
I used specific category  
Or if I prepare earlier tab in game menu for example feat for specific character to add then use that option to pick other character toybox crashes  
So sometimes its just crashes when I try to use search and pick  
Like right know. I was in drezen  
It also crashes when loading blueprints when I wanted to summon some dretches  
Back then i was forced to use search and pick in game menu and then load game and spawn dretch.  
Also resetting only works in game menu.  
Often it crashes when loading is finished  

Source: pawlo41#0198 send me Discord dm

### Steps To Reproduce

Blup

### Toybox Version

1.5.9

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

**Comment by CasDragon** [comment]
Screenshot is dead, perhaps should close?
