### ISSUE TITLE
enemy hp slider not working 

### ISSUE THREAD

**Issue by solo16** [cabarius/ToyBox#109]
as per title the enemy hp multiplier not applying anything to the enemy. I'm using latest ver of the ToyBox 1.2.7 and the game has been updated to 1.0.1c.

**Comment by Jarinex** [comment]
I can confirm it also does not seem to be working for me.

**Comment by solo16** [comment]
> I can confirm it also does not seem to be working for me.

i kinda found a solution ; you need to change the setting under the game difficulty tab and make sure enemy number is set to enlarged, with that set the multiplier works again

**Comment by Jarinex** [comment]
I have that setting turned on, but it still seems to not be working properly.

**Comment by ArcaneTrixter** [comment]
Appreciate @Jarinex looking into this and raising it on the discord. Resolved :)
