### ISSUE TITLE
Companion respec and gestalting

### ISSUE THREAD

**Issue by daroe23** [cabarius/ToyBox#1095]
### Description of the bug

Companions picked up at level 1 are fully functional with careful selection of classes at level 1, there are problems regarding keeping one of the classes as the initial class of the companion, but that is another issue.  However, all other companions do not have full gestalt functionality until achieving the level at which they are recruited. At level 1 you can get it to work but between level 2 and the level at which they were recruited I cannot make choices as far as class feats and bonuses.  The passives, or pre-established things like Sneak dice, or Vital Strike for Rowdy get applied but I can't pick things like Rogue Talents, until after reaching level 4 for the Kenabras recruits.  I can, though, pick other classes at the levels between 2 and recruit level and make choices for those "dips."

### Steps To Reproduce

Open toybox
respec character recruited after level 1 from Toybox or Barley
Choose both classes (problems occur if you select pre-existing class)
Level up and see that you can't make choices for gestalt class until reaching recruit level

### Expected Behavior

Characters were expected to level up with all available class perks

### Toybox Version

1.5.10a

### Operating System

Windows

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.2.4p

**Comment by CasDragon** [comment]
Gestalt bug which is tied to #922
