### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by the-deserter** [cabarius/ToyBox#1096]
### Description of the bug

My game can't load any of my previous saves made using toybox on the latest update of Pathfinder: Wrath of the Righteous

### Steps To Reproduce

1. Open the game
2. Try to load a save file which has previously used toybox/any savefile with toybox installed should do however
3. Get stuck on an infinite loading screen

### Toybox Version

Ver 1.5.10a

### Operating System

Windows

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

24 May 2024	Fri	08:57	No title			14480165

**Comment by CasDragon** [comment]
No logs or information? Alright, I'll guess the problem. You downloaded a mod (outside of Toybox) that created a save dependency, and then uninstalled the mod. Toybox doesn't create a save dependency.

If you want actual help, please fill out the information on the form next time, that's what it's there for. Specifically right now, we would want to look at your log files
https://github.com/cabarius/ToyBox/wiki/Frequently-Asked-Questions#where-are-these-log-files-im-being-asked-for

**Comment by the-deserter** [comment]
> No logs or information? Alright, I'll guess the problem. You downloaded a mod (outside of Toybox) that created a save dependency, and then uninstalled the mod. Toybox doesn't create a save dependency.
> 
> If you want actual help, please fill out the information on the form next time, that's what it's there for. Specifically right now, we would want to look at your log files https://github.com/cabarius/ToyBox/wiki/Frequently-Asked-Questions#where-are-these-log-files-im-being-asked-for

My apologies for the lack of logs, I was under the impression that toybox was at fault from some of nexusmods' newest comments. This is a fresh install of Pathfinder on steam after moving from gog so the only mods I have right now is toybox though I installed previous mods before on my gog save files.

I'll update my issue with the relevant logs

**Comment by CasDragon** [comment]
Your log files are larger then Github will allow? Strange, but I guess it happens. You could use something like Google Drive or Dropbox and use the "Share" link for them, probably.

**Comment by the-deserter** [comment]
> Your log files are larger then Github will allow? Strange, but I guess it happens. You could use something like Google Drive or Dropbox and use the "Share" link for them, probably.

Here's a google drive link to my log files
https://drive.google.com/drive/folders/1jrf5boO8suLD0Gwq4nQ5olKD_m4VvfNY?usp=sharing

**Comment by CasDragon** [comment]
`[Manager] FINISH. SUCCESSFUL LOADED 0/0 MODS.`
Doesn't look like you have Toybox installed?

That being said, I do see an error being spammed (which is likely what is causing your game not to load) It states that your DLC 5 files are corrupted so I'd recommend using the Verify Game Files/Fix Game Files option in your client

**Comment by the-deserter** [comment]
> Did you have DLCs with GoG that you don't have on Steam?

My GOG version lacked the latest DLCs which I got on steam



> `[Manager] FINISH. SUCCESSFUL LOADED 0/0 MODS.` Doesn't look like you have Toybox installed?
> 
> That being said, I do see an error being spammed (which is likely what is causing your game not to load) It states that your DLC 5 files are corrupted so I'd recommend using the Verify Game Files/Fix Game Files option in your client

I uninstalled toybox after I had the problem but nevermind, it turns out that I was missing some dlc files which was the issue 

Will there be an update to toybox when the last dlc drops?

**Comment by CasDragon** [comment]
Yes, Toybox will likely get an update within the first day or so of the DLC/update.
