### ISSUE TITLE
List of features to add/remove under the party tab refresh everytime add/remove is clicked

### ISSUE THREAD

**Issue by RyuKaze78** [cabarius/ToyBox#1098]
### Description of the bug

I have noticed while playing Wrath of the Righteous that when adding features to my character for my umpteenth playthrough that the list refreshes every time to the first page of the results when clicking the add/remove buttons. It did not do this in previous versions. This seems to happen a few minutes after being on the list and can sometimes be bypassed by hitting multiple add/remove buttons quickly. I've tried limiting the results to 100, 300, and 1000 but nothing helps

### Steps To Reproduce

1. Go to Party tab. 2. Click on features arrow to the side of a character's name. 3. Click the show all arrow. 4. Look for a feature or just scroll down the full list. 5. Click the add/remove button

### Screenshots

no screenshots

### Toybox Version

1.5.10a

### Operating System

Windows 10

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

**Comment by CasDragon** [comment]
Can't reproduce on my end. But just to clarify, after you add a feature, the Party tab Features results go from page <whatever> of the results, to page 1 of the results?

Slightly related, for performance reasons, I will recommend you limit the results to like 50, MAX. I personally have my results limited to 15

**Comment by RyuKaze78** [comment]
yeah. If I'm on like page 5 of, say, 10, when I hit the button, it will go back to page 1.

**Comment by xADDBx** [comment]
I finally had some time and had to look at the tab for some time because of another feature

Anyways; the next release will have this fixed
