### ISSUE TITLE
missing features weapon focus and not registered properly

### ISSUE THREAD

**Issue by solo16** [cabarius/ToyBox#110]
just found out not everything is included in the weapon focus features in the search and pick for example glaive and fauchard are missing.

also adding the weapon focus / specialization etc through the search n pick would not registered as acquired feat however it still working properly and apply the improvement correctly however when you level up you could pick the same feature again through natural level up if you do that it'll apply the improvement twice.

**Comment by Jmacq1** [comment]
Adding on to this:  It looks like almost (but not quite) all Exotic Weapons are not included if you search n' pick on Weapon Focus or Weapon Specialization.  For a few regular weapon focus might be available but not greater weapon focus.  Also some non-Exotics are missing as well.  Just off the top of my head Heavy Shield Bash and Longspear aren't showing up, but there are probably others (as noted above).

**Comment by ArcaneTrixter** [comment]
Please use the Parameterized Feats as the other feats are the old Kingmaker versions. For exotic weapon proficiency, you currently need to search the name of the weapon as a feature but there will continue to be enhancements to Search n' Pick.
