### ISSUE TITLE
Always Mount and Naming weapons/smithing weapons through Enhancement Tab

### ISSUE THREAD

**Issue by luqman0102** [cabarius/ToyBox#1105]
### Is your feature request related to a problem?

I'm always frustrated when my character dismounts between fights because the game decided the fight's over when SIKE another fight and I HAVE to re-mount. its annoying.

Also, I have a need to make my own weapons or just rename weapons 

### Describe the solution you'd like

Either there is a way to ensure my character remains mounted after battle or they auto mount when battle starts

would like to see if we can make a smithing feature or just rename weapons through the unity mod manager. kinda like the crafting system in kingmaker: https://www.nexusmods.com/pathfinderkingmaker/mods/54

### Describe alternatives you've considered

there isnt for mounting or smithing or renaming

### Additional context

this is a kingmaker example from nexus mod link; https://staticdelivery.nexusmods.com/mods/2607/images/54/54-1544073934-744777320.jpeg

**Comment by CasDragon** [comment]
Crafting items/renaming items would most likely create a save dependency, and we don't want Toybox to add save dependencies. 

As for mounting, I believe there's already a mod that does this? 
https://github.com/zephe0n/AutoMount
