### ISSUE TITLE
Radiance Sword Loot Color

### ISSUE THREAD

**Issue by Lollerskates** [cabarius/ToyBox#1106]
### Is your feature request related to a problem?

Is there a reason the two first stages of Radiance aren't marked as notable? It would be easy to accidentally sell it, especially in the first stage when it has no color at all.

### Describe the solution you'd like

Maybe Radiance should be marked as notable? Is that even something Toy Box can do?

**Comment by xADDBx** [comment]
ToyBox uses the in game attributes of items.

It's not marked as colored as notable because the game does not mark it as notable.
