### ISSUE TITLE
Toy Box broke my game and I don't know why.

### ISSUE THREAD

**Issue by dasdasddsad** [cabarius/ToyBox#1107]
### Description of the bug

My game version is 2.3.2c and I installed the newest Toy Box with Unity Mod Manager. It broke my game and I don't know why.  I put the bug report below. Can anyone tell me the reason? Thank you very much.

Mono path[0] = 'D:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/Managed'
Mono config path = 'D:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/MonoBleedingEdge/etc'
Initialize engine version: 2020.3.48f1 (b805b124c6b7)
[Subsystems] Discovering subsystems at path D:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 4060 Laptop GPU (ID=0x28a0)
    Vendor:   
    VRAM:     7971 MB
    Driver:   31.0.15.3161
Begin MonoManager ReloadAssembly

[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.27.14.0.
[Manager] OS: Microsoft Windows NT 10.0.22631.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2020.3.481.
[Manager] Game: Pathfinder: Wrath of the Righteous.
[Manager] IsSupportOnSessionStart: False.
[Manager] IsSupportOnSessionStop: False.
[Manager] Mods path: D:\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Mods.
Fallback handler could not load library D:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/Mono/data-000000006E79F060.dll
Fallback handler could not load library D:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/Mono/data-000000006E9DFF10.dll
[Manager] Injection successful.
- Completed reload, in  0.370 seconds
<RI> Initializing input.
<RI> Input initialized.
<RI> Initialized touch support.
[startup.json] Check path: D:\SteamLibrary\steamapps\common\Pathfinder Second Adventure\startup.json
[startup.json] Loaded
UnloadTime: 0.276500 ms
[Manager] Starting.
[Manager] Start parsing game version.
[Manager] Found game version string: '2.3.2c'.
[Manager] Game version detected as '2.3.2'.
[Manager] Parsing mods.
[Manager] Reading file 'D:\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Mods\0ToyBox0\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[0ToyBox0] Version '1.5.5a'. Loading.
Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at UnityModManagerNet.UnityModManager+Logger.Write (System.String str, System.Boolean onlyNative) <0x639fcda0 + 0x00000> in <e2b836aad626492cb17d508e50751848>:0 
  at UnityModManagerNet.UnityModManager+Logger.LogException (System.String key, System.Exception e, System.String prefix) [0x00066] in <e2b836aad626492cb17d508e50751848>:0 
  at UnityModManagerNet.UnityModManager+ModEntry+ModLogger.LogException (System.String key, System.Exception e) [0x00000] in <e2b836aad626492cb17d508e50751848>:0 
  at UnityModManagerNet.UnityModManager+ModEntry.set_Active (System.Boolean value) [0x00155] in <e2b836aad626492cb17d508e50751848>:0 
  at UnityModManagerNet.UnityModManager+ModEntry.Load () [0x008ee] in <e2b836aad626492cb17d508e50751848>:0 
  at UnityModManagerNet.UnityModManager+ModEntry.set_Active (System.Boolean value) [0x00011] in <e2b836aad626492cb17d508e50751848>:0 
  at UnityModManagerNet.UnityModManager._Start () [0x00366] in <e2b836aad626492cb17d508e50751848>:0 
  at UnityModManagerNet.UnityModManager.Start () [0x00009] in <e2b836aad626492cb17d508e50751848>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UnityModManagerNet.UnityModManager:Start()
UnityModManagerNet.Injector:Prefix_Start()
MonoMod.Utils.DynamicMethodDefinition:Kingmaker.GameStarter.Awake_Patch1(GameStarter)

[GameLog] Log Directory: C:/Users/shubn/AppData/LocalLow/Owlcat Games/Pathfinder Wrath Of The Righteous
WwiseUnity: Wwise(R) SDK Version 2019.2.15 Build 7667.
WwiseUnity: Setting Plugin DLL path to: D:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data\Plugins\x86_64
[MonoSingleton] There is no object of type Kingmaker.Utility.CoroutineRunner. Creating new.
[MonoSingleton] There is no object of type Kingmaker.Settings.Graphics.ApplicationFocusObserver. Creating new.
Setting up 8 worker threads for Enlighten.
  Thread -> id: 8bc -> priority: 1 
  Thread -> id: 3d4 -> priority: 1 
  Thread -> id: 4f20 -> priority: 1 
  Thread -> id: 5d14 -> priority: 1 
  Thread -> id: 6424 -> priority: 1 
  Thread -> id: 5624 -> priority: 1 
  Thread -> id: 3c38 -> priority: 1 
  Thread -> id: 2a3c -> priority: 1 

### Steps To Reproduce

When I opened the game with Toy Box installed, the game crashed and showed me the bug report. When I uninstalled the Toy Box, everything was normal.

### Toybox Version

1.5..5a

### Operating System

Windows

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.3.2.c

**Comment by CasDragon** [comment]
> I installed the newest Toy Box

> 1.5.5a

Update your Toybox, 1.5.5a was literally over a year ago.

**Comment by dasdasddsad** [comment]
Excuse me, but I just installed the newest version from the Nexus and it had the same problem

**Comment by CasDragon** [comment]
If the Nexus version doesn't work (Narria isn't available to update Nexus atm), the latest build is here
https://github.com/xADDBx/ToyBox-Wrath/releases/tag/v1.5.22

**Comment by dasdasddsad** [comment]
I am sorry, but it still did not work. I installed the 1.5.22 but it still broke the game and the bug report appeared in the same way.

**Comment by xADDBx** [comment]
Log with the latest version?

**Comment by dasdasddsad** [comment]
Excuse me. Do you mean the GameLog or GameLogPrev

**Comment by xADDBx** [comment]
GameLogFull

**Comment by dasdasddsad** [comment]
[GameLogFull.txt](https://github.com/user-attachments/files/16033770/GameLogFull.txt)

**Comment by xADDBx** [comment]
Have you tried verifying your game files?

**Comment by dasdasddsad** [comment]
I verified the game file with Steam and there is nothing wrong with it. It is complete.

**Comment by CasDragon** [comment]
Only other thing I can thing of is redownloading UMM and reinstalling it? Some file looks to be corrupt, and if it's not a base game file, it's either a corrupted UMM or a corrupted Toybox, I bet

**Comment by dasdasddsad** [comment]
I re-downloaded the UMM and Toybox. When I installed the Toybox, the UMM seemed to break when I launched the game.
