### ISSUE TITLE
"Preview Dialogue Results" option disables dialogue shortcuts when enabled.

### ISSUE THREAD

**Issue by Aranenesto** [cabarius/ToyBox#1109]
### Description of the bug

When enabled, the "Preview Dialogue Results" option prevents the use of keyboard shortcuts in dialogues ( press 1 for dialogue option 1, 2 for dialogue option 2 etc.)  Altered dialogue shortcuts seem to have no effect on the issue, neither does starting a new game / loading existing saves. The feature itself does work.

### Steps To Reproduce

1. Enable "Dialogue Results" under the preview tab in the bag of tricks catagory in the ToyBox mod menu.

2. Enter dialogue with a character.

3. Attempt to press any dialogue shortcut.

### Expected Behavior

Triggering the dialogue option by pressing the assigned key.

### Log Files

[GameLogFull.txt](https://github.com/user-attachments/files/16069291/GameLogFull.txt)

### Save File

[Manual_2_Voidship_Bridge__New_Save__01_33_51.zip](https://github.com/user-attachments/files/16069306/Manual_2_Voidship_Bridge__New_Save__01_33_51.zip)

### Settings

[Settings.zip](https://github.com/user-attachments/files/16069350/Settings.zip)

### Toybox Version

1.5.18

### Operating System

Windows

### What game are you using Toybox on?

Rogue Trader

### Game Version

1.2.0.30

**Comment by CasDragon** [comment]
Can confirm this behavior on my test RT save

**Comment by xADDBx** [comment]
Oh. This is about RT. I just tried to reproduce it in Wrath and was confused ._.

**Comment by xADDBx** [comment]
Fixed in 1.5.21
