### ISSUE TITLE
Game not loading past the 60% mark - sudden incompatibility with TTT?

### ISSUE THREAD

**Issue by h-joerg** [cabarius/ToyBox#1110]
### Description of the bug

The game does not load past the 60% mark anymore. Game was working fine, and worked fine after the release of WOTR patch 2.3.2c, but it won't go past 60% on the initial loading screen anymore. The game, however, loads fine with just Tabletop Tweaks-Base and Tabletop Tweaks-Core installed, or Toy Box by itself, but it won't load with all three enabled at once. Thus I suspect some sudden incompatibility with Tabletop Tweaks.

### Steps To Reproduce

Enable Tabletop Tweaks Base
Enable Tabletop Tweaks Core
Enable Toy Box
Start the game
Game will not load past 60% of the initial load screen

### Expected Behavior

The game should load normally

### Log Files

[GameLog.txt](https://github.com/user-attachments/files/16091565/GameLog.txt)
[GameLogFull.txt](https://github.com/user-attachments/files/16091566/GameLogFull.txt)
[GameLogFullPrev.txt](https://github.com/user-attachments/files/16091567/GameLogFullPrev.txt)
[GameLogPrev.txt](https://github.com/user-attachments/files/16091568/GameLogPrev.txt)
[Player.log](https://github.com/user-attachments/files/16091569/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16091570/Player-prev.log)

### Toybox Version

1.5.13

### Operating System

Windows 10

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.3.2c

**Comment by CasDragon** [comment]
`[0ToyBox0] Version '1.5.13'. Loading.`

Update your Toybox, you are pretty far out of date. Narria hasn't been around to update the Nexus page, so here's the link to it.
https://github.com/xADDBx/ToyBox-Wrath/releases/tag/v1.5.24

**Comment by h-joerg** [comment]
Thanks, that was it.
