### ISSUE TITLE
ToyBox 1.5.24 crashes Unity Mod Manager config window

### ISSUE THREAD

**Issue by h-joerg** [cabarius/ToyBox#1111]
### Description of the bug

When starting the game, my Player.log file pops up. The game proceeds to load as normally, but the Unity Mod Manager config window is not present in the game's main menu, nor can you toggle it with Ctrl+F10. It shows up as expected as long as ToyBox is deactivated.

### Steps To Reproduce

1. Install ToyBox 1.5.24
2. Start the game
3. At the main menu, UMM config window is not present nor can it be toggled on

### Expected Behavior

UMM config window should be present once the game enters game menu

### Log Files

[GameLogFullPrev.txt](https://github.com/user-attachments/files/16097679/GameLogFullPrev.txt)
[GameLogPrev.txt](https://github.com/user-attachments/files/16097680/GameLogPrev.txt)
[Player.log](https://github.com/user-attachments/files/16097681/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16097682/Player-prev.log)
[GameLog.txt](https://github.com/user-attachments/files/16097683/GameLog.txt)
[GameLogFull.txt](https://github.com/user-attachments/files/16097684/GameLogFull.txt)

### Toybox Version

1.5.24

### Operating System

Windows 10

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.3.2c

**Comment by xADDBx** [comment]
Have you tried verifying your game files?
If that doesn't work, maybe try reinstalling UMM. The error in your log is... weird.

**Comment by CasDragon** [comment]
For reference by what ADDB calls "weird", the log is saying that UMM itself is crashing (due to an invalid logger?). Obviously, that's not normal, so it's possible that either one of the UMM files is corrupted, or one of your game files is corrupted

**Comment by h-joerg** [comment]
So I've tried the following
- verified my game files
- uninstalled UMM through the uninstall function inside the program
- deleted the UMM related files from the game folder
- deleted the UMM related fiels outside of the game folder
- did a fresh "install" of UMM
No changes at this point
- did all of the above, but also uninstalled the game and related all config and save related files
- reinstalled the game
- reinstalled UMM
- reinstalled ToyBox
The issue remains the same, I get a Player.log popup, and the config menu isn't here.
Again, this is only an issue with ToyBox, I can run the game with other mods (TTT. BubbleBuffs) just fine

[GameLogFullPrev.txt](https://github.com/user-attachments/files/16100560/GameLogFullPrev.txt)
[GameLogPrev.txt](https://github.com/user-attachments/files/16100561/GameLogPrev.txt)
[Player.log](https://github.com/user-attachments/files/16100563/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16100564/Player-prev.log)
[GameLog.txt](https://github.com/user-attachments/files/16100565/GameLog.txt)
[GameLogFull.txt](https://github.com/user-attachments/files/16100566/GameLogFull.txt)

EDIT: Another thing, this was not an issue when using version 1.5.13. But that one suddenly became incompatible with TTT so I had to update. Well, not both mods have no issues loading at once, but I can't configure them at all in-game.

**Comment by xADDBx** [comment]
I can't reproduce. Neither can other modders.
None of us can even guess what could be the reason without attaching a Debugger.

Are you by chance blocking web requests? That shouldn't cause an issue normally, but I really can't say what's the problem here.

**Comment by xADDBx** [comment]
Somebody created a changed UnityModManager.dll. Replace your existing one (located in `Steam\steamapps\common\Pathfinder Second Adventure\Wrath_Data\Managed\UnityModManager`). Then try again. Please do share your logs again too. This files should have better logging.

File Link (it's the dl link from Discord, if it for you doesn't work I'll reupload myself)

https://cdn.discordapp.com/attachments/791053285657542666/1259503988278165596/UnityModManager.dll?ex=668bebff&is=668a9a7f&hm=9e5da4ebf50de510abc0a9f51f152f53fad18e818586561b7c5f3bdeba405609&

**Comment by h-joerg** [comment]
Here are the logs as requested with the new .dll, from a "crashed" launch
[GameLogFull.txt](https://github.com/user-attachments/files/16120104/GameLogFull.txt)
[GameLogFullPrev.txt](https://github.com/user-attachments/files/16120105/GameLogFullPrev.txt)
[GameLogPrev.txt](https://github.com/user-attachments/files/16120106/GameLogPrev.txt)
[Player.log](https://github.com/user-attachments/files/16120107/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16120108/Player-prev.log)
[GameLog.txt](https://github.com/user-attachments/files/16120109/GameLog.txt)

I've also been trying whatever I can to get it to work and I finally managed it - if I use the Assembly install method for UMM instead of DoorstopProxy, the game starts normally as expected. Crashes however still occur if I use DoorstopProxy for any ToyBox version past 1.5.13.

**Comment by aaronmaslen** [comment]
If you're using Assembly install method, you should install WrathPatches and use it to upgrade Harmony or you will be stuck on an old version that may break certain mods.

**Comment by xADDBx** [comment]
I'm glad it worked out for you; still at this point nobody on our side could reproduce; the thoughts we did have for debugging (i.e. custom assemblies) didn't work out.

Since there's nothing more we can do for now I'll close until any new development regarding this occurs.

**Comment by xADDBx** [comment]
I think this will be fixed in 1.6.7 when it releases.
We tracked down the source (though it doesn't make much sense), and did some changes that seems to have resolved the problem...
