### ISSUE TITLE
 Game crashes randomly since updating to patch 2.3.3j

### ISSUE THREAD

**Issue by mrsheeper** [cabarius/ToyBox#1113]
### Description of the bug

Since updating to todays patch 2.3.3j game has been crashing consistently every 5 to 15 mins
gameplay was completely smooth before this patch and a clean install has not fixed the issue.
playing without the mod stops the issue from happening
at the start it was mostly in loading screens but it appears to happen anytime whether it be during crusade battles or travelling the map or book events i was unable to find a specific trigger for the crash
it even happened once while trying to mess with the mod settings

### Steps To Reproduce

1. open the game and load a save
2. play normally
3. after more or less 10 minutes game crashes 

### Log Files

[GameLog.txt](https://github.com/user-attachments/files/16182857/GameLog.txt)
[GameLogFull.txt](https://github.com/user-attachments/files/16182858/GameLogFull.txt)
[GameLogFullPrev.txt](https://github.com/user-attachments/files/16182859/GameLogFullPrev.txt)
[GameLogPrev.txt](https://github.com/user-attachments/files/16182860/GameLogPrev.txt)
[Player.log](https://github.com/user-attachments/files/16182861/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/16182862/Player-prev.log)

### Save File

[Saved Games.zip](https://github.com/user-attachments/files/16182891/Saved.Games.zip)
[Saved Games2.zip](https://github.com/user-attachments/files/16182927/Saved.Games2.zip)

### Settings

[Settings.zip](https://github.com/user-attachments/files/16182942/Settings.zip)

### Toybox Version

1.5.24

### Operating System

Windows 10

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.3.3j

**Comment by xADDBx** [comment]
Have you tried verifying game files?

**Comment by mrsheeper** [comment]
i tried reinstalling the mod as well as unity mod manager to no avail. verifying game files also didn't solve the problem.
ended up doing a completely clean reinstall of the game which resolved the issue so unfortunately i'm not sure what the actual problem was
