### ISSUE TITLE
Include Charge Buff, Cleave Buff, Power Attack Buff to Buff Duration Exception.

### ISSUE THREAD

**Issue by caloyers** [cabarius/ToyBox#1116]
### Is your feature request related to a problem?

I cant manually add them in buff duration exception as the search for these does not appear.

### Describe the solution you'd like

Add the following to the Buff Duration Exception(Bag of Tricks/Other Multipliers) as this three is hidden in the list.

Charge buff:  f36da144a379d534cad8e21667079066
Cleave Penalty Buff(AC Penalty):  914b04c279e3d3447848fecf5796cdcd
Power Attack Buff: bfe8300529214c7ca4ae0024f834f085

Charge buff penalty disables activation of stealth mode and even invisibility will trigger an attack from enemies.

**Comment by xADDBx** [comment]
Wait what.

There's buffs that are included but aren't visible in the exclusion editor?

@CasDragon thoughts?

**Comment by CasDragon** [comment]
I'm like 60% sure those buffs aren't being affected by the Duration Multiplier to being with, which is why it's not showing up in the exclusion editor.

That said, I'm sure it would be fine if we manually added them to the exclusion list, so perhaps we do that, and we'll just call this "fixed"

**Comment by xADDBx** [comment]
Huuh. I thought we filtered every hidden bp from being multiplied...

Filter for multiplier:
```
private static bool isGoodBuff(BlueprintBuff blueprint) => !blueprint.Harmful && !badBuffs.Contains(blueprint.AssetGuidThreadSafe);
```

List of buffs for Exclusion Editor:
```cs
_allBuffs = BlueprintLoader.Shared.GetBlueprints<BlueprintBuff>()
                    ?.Where(bp => !bp.IsHiddenInUI
                                  && !bp.IsClassFeature
                                  && !bp.Harmful)
```

**Comment by xADDBx** [comment]
Try to see if the new version fixes your issue @caloyers

**Comment by caloyers** [comment]
Thanks it fixed now. Please close.
