### ISSUE TITLE
Companion respec from zero breaks gestalt completely

### ISSUE THREAD

**Issue by NakedGranny** [cabarius/ToyBox#1117]
### Description of the bug

It's not necessarily a problem of ToyBox all by itself, but any method by which companions may be respec'd from level 0 seems to completely break the gestalt feature. Specifically, only one class is progressed, while none of the gestalt class's class features are added. For example, if you take Fighter as a gestalt-flagged class, you don't get any of the bonus combat feats it can provide - but strangely enough it seems that your raw Fighter class level is used to determine whether you qualify to buy Weapon Training and Armor Training -related Feats with your base character feat slots. You do not get to pick any class-feature related options from your gestalt class(es) while leveling up.

Worse, if you level up a single class while taking a dip into a second class just normally according to baseline default Pathfinder rules, if you then flag as gestalt the class with more levels so that you can then level up the "dipped" class, the gestalt feature will preserve all your HD and things so you end up with radically inflated hit points and skills and things. In other words, the gestalt feature of ToyBox is not tracking what characters are supposed to have if they were created as gestalt characters, it's just toggling flags and letting the engine progress characters as if it were correct.

### Steps To Reproduce

1. Use any of the "fully respec companions" mod options available
2. Select any multiclassed companion character in ToyBox and designate any classes as gestalt for them.
3. Then click respec (or use Hilor)
4. None of the gestalt-flagged classes are preserved as gestalt: the respec will proceed according to vanilla
5. If you interrupt the respec process after designating a single class to start with in order to add any gestalt flagged classes, they are ignored in terms of their class features but their class levels (NOT their actual features) are still accounted for when determining what feats and prestige classes you can qualify to get.

### Expected Behavior

Hopefully ToyBox can take into account any of the fully-respec-companions mods to correct this behavior.

Companions should be treated like generating the main character from scratch, by designating specific classes as gestalt for them and then entering character generation so that they are calculated correctly.

In the past, other users have claimed that you can workaround this by carefully designating which classes are gestalt according to their appearance on the list of classes in Toybox - this is not working at all. It does not matter which order you flag the classes in, in ToyBox or in the levelup class selection screen in-game. None of those workaround methods are working currently.

### Toybox Version

1.5.28

### Operating System

Windows

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.3.3k

**Comment by xADDBx** [comment]
#1095 which itself has been linked to #922

I'd suggest taking a look at the [mod which sets default companion level to 1](https://github.com/CasDragon/lvl1companions); it might change behaviour? @CasDragon because I don't exactly remember the issue.

**Comment by NakedGranny** [comment]
> #1095 which itself has been linked to #922
> 
> I'd suggest taking a look at the [mod which sets default companion level to 1](https://github.com/CasDragon/lvl1companions); it might change behaviour? @CasDragon because I don't exactly remember the issue.

Thank you for your reply - do you know much about how that mod works? I don't really understand how setting their join levels to 1 would help with compatibility between the level 0 respec mod and ToyBox's gestalt.

Ninja edit: Reviewing my installed mods, I'm apparently using [a companion respec mod from someone called PSCZ](https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/309) which they claim is an updated version of [one by Aephiex which was last updated on Nexus in 2021](https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/203). If Barley put out a mod that does the same thing, I need to go hunting for it.

**Comment by xADDBx** [comment]
> > #1095 which itself has been linked to #922
> > I'd suggest taking a look at the [mod which sets default companion level to 1](https://github.com/CasDragon/lvl1companions); it might change behaviour? @CasDragon because I don't exactly remember the issue.
> 
> Thank you for your reply - do you know much about how that mod works? I don't really understand how setting their join levels to 1 would help with compatibility between the level 0 respec mod and ToyBox's gestalt.

To quote one of the linked issues 

> Companions picked up at level 1 are fully functional with careful selection of classes at level 1, there are problems regarding keeping one of the classes as the initial class of the companion, but that is another issue. However, all other companions do not have full gestalt functionality until achieving the level at which they are recruited. At level 1 you can get it to work but between level 2 and the level at which they were recruited I cannot make choices as far as class feats and bonuses. The passives, or pre-established things like Sneak dice, or Vital Strike for Rowdy get applied but I can't pick things like Rogue Talents, until after reaching level 4 for the Kenabras recruits. I can, though, pick other classes at the levels between 2 and recruit level and make choices for those "dips."

The mod changes the mentioned "Recruit level" to 1. (This also means that default Hilor respec will still let you respec from level 1!). If this is the issue you're encountering, then installing the mod might fix it for you.

As for why this is an issue, I can't say. Probably nobody can since nobody looked at Gestalt code for a while.

Also yes, BarleyRespec is supposed to be preferable (though if you only want to respec companions from level 1 just use that other mod that changes default level)

**Comment by NakedGranny** [comment]
I appreciate you, thank you. Will spend a little time fussing with it to see if I can hot-swap mods on an in-progress playthrough. Might need to start a new playthrough just to be sure if it doesn't work quite right this time?

**Comment by NakedGranny** [comment]
Currently it seems Barley's mod in combination with CasDragon's level 1 mod does mostly work, but incompletely.

It seems that after you initiate the respec, the first level is single classed, and when you take character level 2, you gain level 1 in your gestalt class. This means that your gestalt class remains one level behind your character level. It's not ruinous, but it's definitely not perfect.

**Comment by CasDragon** [comment]
I recommend you come into the Discord at this point. This is a duplicate issue, with a workaround that was listed. Further, Level 1 Companions + Barley Respec does allow for people to gestalt correctly from level 1 (multiple people use the combination daily with no issues), so whatever your issue is, its likely on your end, and we can help debug it in the Discord or even on my Github page for the Level 1 Companions mod (which I only check once a day, so reply time is slow)

**Comment by xADDBx** [comment]
https://github.com/xADDBx/ToyBox-Wrath/releases/tag/v1.5.37
