### ISSUE TITLE
Change Dismiss infusion / spell to a swift action

### ISSUE THREAD

**Issue by highfly117** [cabarius/ToyBox#1119]
### Is your feature request related to a problem?

Currently Dismiss infusion / spell is a standard action this waste a characters whole round just to remove a spell 

### Describe the solution you'd like

Change Dismiss infusion / spell so that it is a swift action but can't be done in the turn you cast the spell or infusion

**Comment by xADDBx** [comment]
Out of scope for ToyBox.
Seems like it might not be too hard to implement as a separate mod; maybe ask on the Discord if someone could implement this?
