### ISSUE TITLE
Free actions cost Move actions

### ISSUE THREAD

**Issue by Truinto** [cabarius/ToyBox#112]
https://github.com/cabarius/ToyBox/blob/3be6f5916b417eaeb61e637388b060a80a4c541b/ToyBox/classes/MonkeyPatchin/BagOfPatches/Tweaks.cs#L356

Was looking for a different bug. But this line cannot be correct. While not in turn-based, any free action costs a move action instead. Looking at the game's source, there is a break; missing.

**Comment by Deltharis** [comment]
Fixed in 1.2.9
