### ISSUE TITLE
ToyBox 1.6.0 can't add skills to generals 

### ISSUE THREAD

**Issue by jackpotzero** [cabarius/ToyBox#1124]
### Description of the bug

After the new fast bp loading system, you can no longer add skills to army generals because no matter what you type in the skill list is always empty

### Steps To Reproduce

Go to Armies (ToyBox menu)
Inspect one of your generals
Click "Show all" next to "Skills"
The list is always empty

### Expected Behavior

Go to Armies (ToyBox menu)
Inspect one of your generals
Click "Show all" next to "Skills"
You get a list of every single general skill in the game 

### Toybox Version

1.6.0

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

**Comment by xADDBx** [comment]
Logs? Screenshots? Other mods?

**Comment by jackpotzero** [comment]
When I click "Show all" under my general skills, i get an empty list and the logs show me this:
[0ToyBox0] [Info] Glyph Support Check returned: True
[0ToyBox0] [Info] Loading 277 Blueprints
[0ToyBox0] [Info] Threaded loaded 277 blueprints in 2919 milliseconds

No Errors, so I assume general skills aren't included in those 277 ? 
I enabled "Preload Blueprints" and its fixed now, i get the full skill list as intended !

it seems I have to preload blueprints whenever I want to edit a general, which is fine since I don't edit generals that often
other features (adding spells, feats, buffs) works fine without preloading btw, its only general skills. 

Mods:
0ToyBox0
AlternateRacialTraits
BubbleBuffs
CharacterOptionsPlus
CustomNpcPortraits
DarkCodex
ExpandedContent
KineticistElementsExpanded
MicroscopicContentExpansion
ModMenu
MythicMagicMayhem
OnePearl
PrestigePlus
SpellbookMerge
TabletopTweaks-Base
TabletopTweaks-Core
TabletopTweaks-Reworks
VisualAdjustments2
WOTR_PATH_OF_RAGE

**Comment by xADDBx** [comment]
I haven't tested it, but I'm pretty sure this will fix the issue
[ToyBox-1.6.2.zip](https://github.com/user-attachments/files/16851935/ToyBox-1.6.2.zip)
