### ISSUE TITLE
Light mode.

### ISSUE THREAD

**Issue by bittercranberry** [cabarius/ToyBox#1126]
### Is your feature request related to a problem?

Toybox is very dark, hard to read.

### Describe the solution you'd like

Light mode.

### Additional context

![image](https://github.com/user-attachments/assets/eb503f43-77e1-4a5d-8a34-7b90e5bdf0b9)
So pretty!

**Comment by CasDragon** [comment]
No

**Comment by xADDBx** [comment]
Since another Collaborator already gave a very insightful response on this issue I'll close it for now.
