### ISSUE TITLE
Allow Equipment Change During Combat not working

### ISSUE THREAD

**Issue by The-Talik** [cabarius/ToyBox#1128]
### Description of the bug

With this option checked (checked since I loaded the game), I can not change equipment during combat.

### Steps To Reproduce

Enable option.  Try to change equipment.

### Toybox Version

1.6.3

### Operating System

Windows 11

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.4.0x (I think)

**Comment by CasDragon** [comment]
Fixed in one of the new versions, pretty sure

**Comment by xADDBx** [comment]
I completely ignored this thinking it was about Rogue Trader...
