### ISSUE TITLE
Starting daeran's romance via toybox breaks the romance encounters

### ISSUE THREAD

**Issue by franxisfaxz** [cabarius/ToyBox#1129]
### Description of the bug

i lost the oportunity to romance daeran early in chapter 1 and 2, on chapter 3 while in drezen i enabled both the daeranromance and daeranromanceactive in search n pick to enable the romance and that breaks the romance events in the command room, daeran appears outside the map and the screen goes black, but i still can select answers to his dialogue, on the quest Not A Date the same thing happens but when the scene changes and its loading it crashes to the main menu giving me this error

![20240930193318_1](https://github.com/user-attachments/assets/ff1e2818-31d7-4208-8383-05ee293efc69)

### Steps To Reproduce

1. go to chapter 3 start
2. enable romance via toybox search n picks
3. wait for a command room romance event

### Toybox Version

1.6.7

### Operating System

Windows 11

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.4.1i

**Comment by CasDragon** [comment]
Breaking your game by starting etudes isn't a Toybox bug. If you don't know what you are doing with etudes/flags/etc,  you can severely break your save file.

**Comment by xADDBx** [comment]
The thing is, there are many Etudes in the game. Experimenting without knowing what you're doing can sometimes help you, while other times it will just cause issues nobody will be able (or willing) to understand.

For future reference, I'd suggest replaying the part that you missed and checking which etudes are actually affected by the game (using the history file in the save or by enabling dialog preview ToyBox option) and then replicating those.

**Comment by franxisfaxz** [comment]
damn, thanks for the response, i'll see if i can fix it on my own
