### ISSUE TITLE
Feat multiplier when you get a new companion

### ISSUE THREAD

**Issue by LukeRibbons** [cabarius/ToyBox#121]
Feat multiplier apples to companions previous levels when you get them, I accidentally ended up with a Nenio who had every opposition school other then illusion and was pretty useless lel. Main fix is to not leave it active but if you forget it causes these issues.

**Comment by wolfplank** [comment]
Same.

**Comment by LadyAlekto** [comment]
TBF Nenio is the only companion where its detrimental

All other companions get quite some neat buffs

**Comment by LukeRibbons** [comment]
I think it could cause issues on ones that also have negatives at start, like curses on Daeran. And possibly other issues down the line.

**Comment by ArcaneTrixter** [comment]
This appears to be resolved as of 1.3.5. If this is still an issue let me know, otherwise I'll close this.
