### ISSUE TITLE
QOL shortcuts request

### ISSUE THREAD

**Issue by YunSoja** [cabarius/ToyBox#128]
Hello,

Could you please add the following editable shortcuts for the selected character(s) :
One to switch weapons sets
One to toggle on and off the sneak ability
One to toggle on and off the ai
One to tp on the cursor
I think it would be some great QOL features.

Thank you for your work, it's a great mod already.

**Comment by DreamTourist** [comment]
Check out [Hotkeys for Weapon Sets - AI and Stealth](https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/68) mod over at Nexus.

**Comment by YunSoja** [comment]
Tyvm !

**Comment by ArcaneTrixter** [comment]
Shortcut keys are added to (many) things in Toybox now. For in game shortcuts, I suspect apocc's mod (above) has that more in scope.
