### ISSUE TITLE
Preview Dialog Results

### ISSUE THREAD

**Issue by BrutaleBent** [cabarius/ToyBox#13]
Preview Dialog Results, as per the Kingdom Resolution mod for PF: Kingmaker (so you don't go "oops, you picked the wrong dialog option 80 hours ago, tough luck").

Picture example: https://staticdelivery.nexusmods.com/mods/2607/images/36/36-1542719876-190482702.png

Also honorable mentions, if they're present in the game:
Preview Event Results 
Preview Random Encounters

**Comment by cabarius** [comment]
this is a great suggestion
