### ISSUE TITLE
Clarification - How to add a parameterized feat?

### ISSUE THREAD

**Issue by v-echo** [cabarius/ToyBox#142]
Like title says, I can't figure out where to find the possible parameters for the feats like Weapon Focus etc.
The regular weapon focus (specific weapons) can be found in Search'n'Pick, but it gets placed in Abilities rather than Feats. 
The mythic version doesn't have specific weapon feats, only the generic one. And I don't see a way to parameterize it correctly.

**Comment by ArcaneTrixter** [comment]
This has been added since this issue was created; go to search n' pick and select the Parameterized Features selection on the left side (or simply search under All).
