### ISSUE TITLE
Request: Romance counters

### ISSUE THREAD

**Issue by Kajosiv** [cabarius/ToyBox#150]
Great to have this mod in WotR, really having fun playing around with it. Would be possible to have Romance counter in this as well like in the original bag of tricks for kingmaker? Romances seem to be bit messy, and half the time I got no idea if it was because of script or if the counters are bugged. Also it was jolly fun to mess around with in Kingmaker, would be fun to do it in WotR as well.

Thanks for the great mod in any case.

**Comment by Deltharis** [comment]
After investigating it turns out, that WotR no longer uses romance counters as means to track romance progress. There are only two counters in the game, and they're both unusable. Current system is most likely based on etudes.

**Comment by Kajosiv** [comment]
Thanks for the reply! Ah I see, makes sense. I've been playing with previews of dialogue and noticed it's mostly etudes that change between choices. I guess that makes it a bit more complicated. 
Bit of a side note but what about flags? Seems like they are not used for romance as such but there seem to be stuff like Daerans trust, and Woljifs human/Demon ending coming up in the preview dialogue?
