### ISSUE TITLE
Add an option to remove the dexterity cap on armor

### ISSUE THREAD

**Issue by rcd1976** [cabarius/ToyBox#155]
Bag of tricks for Kingmaker had a selectable feature that effectively removed the dexterity bonus cap  for all armors. I believe it did this by raising the cap to +99. Could you please add such a feature to Toybox?

**Comment by ArcaneTrixter** [comment]
Done.

**Comment by rcd1976** [comment]
Wow thanks

That happened much faster than I anticipated.

**Comment by ArcaneTrixter** [comment]
Can we mark this one as closed? :)

**Comment by rcd1976** [comment]
Sure

Is that something I do, or can you close it?

**Comment by ArcaneTrixter** [comment]
Think it's got to be you or Cabarius. If you can go ahead and mark it closed that'd help though :)
