### ISSUE TITLE
[bug] "Refilll Consumables in belt slots if in inventory" destroys reuseable consumable items

### ISSUE THREAD

**Issue by TheOneDoc** [cabarius/ToyBox#161]
Version 1.2.13
Reusable Consumable items like Pipefox, Headchomper, Dark Veil, Tankard of Free Spirit do disaapear permanently from the character and shared inventory when this function is active. 

Seems like a blacklist is needed for reuseable consumables.

**Comment by Jayshua83** [comment]
Yeah. I just had Toy Box remove the Covenant of the Inheritor item from my belt slot!
