### ISSUE TITLE
Experimental multiple romances?

### ISSUE THREAD

**Issue by Kajosiv** [cabarius/ToyBox#173]
Soooo, what's the option supposed to do? I was playing a lich run, had the option on, and when I got back to Drezen and conquered the citadel back, afterwards I still got the event for choosing one romance from the ones I was pursuing, making multiple romances impossible.

**Comment by cabarius** [comment]
Please come onto our discord https://discord.gg/PPHaH9sj and find me (Narria) and please DM me a save where you are right at this decision point.  It will help us debug this.
