### ISSUE TITLE
Whole Team Moves Same Speed not working

### ISSUE THREAD

**Issue by SnowbankDev** [cabarius/ToyBox#178]
I'm trying to use the Whole Team Moves Same Speed tweak as I have Lann in my team with fast movement from monk who runs about 10,000 miles ahead of the rest of my party unless I micro my movement very carefully.

Unfortunately, checking the toggle doesn't seem to have any effect, unless the problem is me :)

**Comment by Jayshua83** [comment]
Yeah. I have noticed this too!

**Comment by cabarius** [comment]
Fixed in 1.3.0
