### ISSUE TITLE
toybox pathfinder

### ISSUE THREAD

**Issue by lokixxxloki** [cabarius/ToyBox#182]
i have taked this address from another site where i have found toybox and in file description is write to report there bug or similar.
i have do the update of game ﻿patch_pathfinder_wrath_of_the_righteous_1.0.0s_(49717)_to_1.0.1c_(49813) and toybox don't work anymore.
i have try to uninstal and reinstall toybox but nothing change.
exist one updated version of this editor that can work on game version 1.0.1c ? or i must  uninstal the game do the mod that i need and after i can reupdate it ? thx

**Comment by cabarius** [comment]
I am on 1.0.2g and it works fine for me. I would recommend you move to that.

**Comment by lokixxxloki** [comment]
i have solved, i have uninstalled the game via revouninstal for delete every single file (i have do a copy of save game) of the game and after i have reinstalled a new and clean installation and now work, problably during the installation of patch some file has been ruined. sorry for useless post

**Comment by cabarius** [comment]
no problem ^_^
