### ISSUE TITLE
Player character swapped to NPC Companion

### ISSUE THREAD

**Issue by nagard1990** [cabarius/ToyBox#192]
The player character was swapped to a Seelah, which results in weird behaviour when entering ares in which only the player character can be controlled (for example Defender's Heart).

In the party editor I can "Remove" the PC, but not Seelah. Unfortunately I have no idea what caused this nor when it did happen, but I do assume it happened when I rearranged my partyorder at the bottom of the screen.

**Comment by EnderWiggin** [comment]
Happened to me when I tried levelling up with main class marked as gestalt. Levelup screen was all borked. You can try to modify player.json inside save file to fix that.

**Comment by nagard1990** [comment]
Hi EnderWiggin

Thank you very much for your tip. I managed to swap the entry "m_MainCharacter" with one from an older save and the save is now working again.

**Comment by ArcaneTrixter** [comment]
I've added a button to toybox to fix it from within the game, and made it (at least more difficult) to cause this scenario by making it so you can't select both classes as gestalt.
