### ISSUE TITLE
Feature request: ignore mythic path dialog and crusader restrictions

### ISSUE THREAD

**Issue by Bleaktee54** [cabarius/ToyBox#197]
Would be at all possible to have the ability to ignore mythic path dialog restrictions for both normal dialog as well as crusader choices? So, for instance, even if we chose the trickester path, we could still choose the lich option to resurrect staunton or the aeon option of redeeming him. Likewise, we would be able to choose the azata option in a crusader/kingdom managment choice. 

Thank you in advance and thank you for the fun mod.

**Comment by cabarius** [comment]
Can you come onto our discord? https://discord.gg/wotr
and find me there (Narria) and DM me a save where you are before a path and crusader restricted dialog?  That would help me do this.

**Comment by Bleaktee54** [comment]
> Can you come onto our discord? https://discord.gg/wotr
> and find me there (Narria) and DM me a save where you are before a path and crusader restricted dialog? That would help me do this.

Im already part of the discord and you bet! I would love to help. Give till some time this afternoon, and i should have a few saves to help. Ill include info in the DM about what to look for. Thank you.

**Comment by kbaegis** [comment]
Where did this end up?

**Comment by kbaegis** [comment]
Whatever is being done with the dialogue state checking cannot be resolved cleanly with the following variables via toybox:
```
PlayerIs<Mythic>
PlayerWas<Mythic>

18!.##_MythicChoices_<Mythic>
18_Mythic Choices_NOT

##_PathOf<Mythic>

46!_AllPathsOpen_checker
46_AllPathsOpen

<Mythic>Path
46!.0_path_open_sum
```

The available options with toybox aren't sufficient to resolve this.

**Comment by kbaegis** [comment]
Specific scripted conditions are pinned to individual answers. In my case- Answer_0023 is failing, but I can't seem to figure out what the scripted conditions it's checking for are.

It would be helpful if the variables it were checking were at least consistently formatted. :/

**Comment by kbaegis** [comment]
I think this is under Kingmaker.ElementsSystem.ConditionsHolder at node ae23d8ef3f5e9024d9d5b9fa6ba8f19a. It's reading something from under the Etudes system like AngelChosen: Playing, but I can't seem to get it working. Maybe someone else can pick this back up. :D

**Comment by kbaegis** [comment]
I think this is evaluated when the dialogue options come up at AnswerList de1e8e44fc1139c40bb04209e5e8b75d.
