### ISSUE TITLE
Most Choices Clear after attempting to enter name and "gestalted" classes lose their archetypes (just noticed you asked bugs to be posted here)

### ISSUE THREAD

**Issue by NeutralGoodGamer** [cabarius/ToyBox#199]
I'm not sure what is causing it especially since I've tried other combinations (ie. Rogue/Fighter/Barbarian, Sensei Monk/Enligntened Oracle, etc.) and I don't have the same issue here's my choices (note this happens whether im choosing cleric, monk or oracle as my "primary" class. this also happens whether i'm creating a new game or using respec in your mod)

Mods in use: Only this one
Portrait: 4th WOTR one, monk guy w/ quarterstaff
Classes: Priest of Balance Cleric, Sensei Monk, Vanilla Oracle (same thing w/ just oracle and cleric or monk and cleric...i think cleric is the issue tbh although it works fine when i'm not using the mod)
Race: Aasimar (default aasimar for +2 Wis/Cha)
Background: Scholar (Divine)
Stats: Str10/Dex8/Con12/Int14/Wis18/Cha18
Skills: Religion, Perception, Persuasion, UMD (the available skill points seems to rely on the "primary" class, its 7 if i choose oracle in-game for example despite having "highest applies" chosen)
Feat: Selective Channel
Deity: Nethys
Domain: Magic
Monk Bonus Feat: Crane Style
Curse: Pranked
Mystery: Nature
Revelation: Nature's Whispers
Additional Spells: Inflict
Choose Spells: Command, Remove Sickness 
Choose Alignment: Lawful Neutral
Visual Stuff: Leave at default or customize it all doesn't matter
Voice: Male Wise
Name: Gibberish, a real name or use the name generator doesn't matter

Than attempt to click next but its greyed out saying "character's name has not been chosen" i try re-entering it, making it longer shorter, smacking the random button a few times, change the birthdate, etc, etc. and nothing will satisfy the game enough to click "next" it just keeps saying "character's name has not been chosen"

After that if you look at the top all your choices have cleared back to "skills" and you have more skill points to spend so you can either click the back button or click on skills (or quit)

Doing so reveals that the skills you chose before still have skill points spent on them but you can spend them again (seemingly 1+w/e skill pints you had the first time)

At this time if you go back to class selection you can see that your classes are now whatever you chose for your primary class (you can still change this) and your "extra" classes are still their but they've lost their archetypes (if any)

**Comment by SoulInShadow** [comment]
As a workaround, the archetypes can be restored by going back to the class selection page, selecting another class/archetype and then selecting the one you wanted again. Presumably the game loading the class progression tables reloads the archetype choices. Also useful if you decide to change your mind on a particular class/archetype part way through the process, rather than completely exiting character creation

**Comment by DreamTourist** [comment]
Is this bug still happening?
It was fixed when I tested it on v1-3-0.

**Comment by DreamTourist** [comment]
Update for ToyBox v1-3-2.

Just ran a quick test in Character Creation.
ToyBox >  Level Up > Class Selection > Char Gen >  Alchemist > Vivisectionist
ToyBox >  Level Up > Class Selection > Char Gen >  Monk
Character Creation > Class > Kineticist
Got to Result tab perfectly fine without breaking at Name tab.

Second test.
ToyBox >  Level Up > Class Selection > Char Gen > Cleric > Priest of Balance
ToyBox >  Level Up > Class Selection > Char Gen > Monk > Sensei
Character Creation > Class > Oracle
Same, got to Result tab perfectly fine.
*had to pick Deity before I could choose a Domain, but was able to move & switch tabs without any problems.

**Comment by NeutralGoodGamer** [comment]
I just download the mod yesterday so i have the most recent one...unless the one on nexus is outdated

**Comment by DreamTourist** [comment]
Nexus is up to date, just remember to use the one under Main Files.
The one under Optional files is outdated, from Cabarius was testing the mod's Multiple Classes feature.

**Comment by NeutralGoodGamer** [comment]
OH!!! I was using the optional one i though the other version didn't have gestalt yet, if it matters i have the Gog version of WOTR

**Comment by DreamTourist** [comment]
Yup, thats your problem right there.
The optional one (v1-2-13-1 (Experimental)) has a lot of bugs.
Cabarius officially included the Multiple Classes feature in the main mod with v1-3-0. Plus, the mod works fine on both Steam & GOG.

**Comment by NeutralGoodGamer** [comment]
Yup guess i was just too excited to notice :D
