### ISSUE TITLE
Only "Primary" class gets new spells upon level up (Gestalt issue)

### ISSUE THREAD

**Issue by NeutralGoodGamer** [cabarius/ToyBox#205]
Pretty much the title, have the most up to date version this time

"Primary" - Monk Sensei (wanted the monk outfit)
"Gestalt" - Priest of Balance Cleric/Enlightened Philosopher Oracle

In this case cleric SEEMS to be gaining spells since its automatic (clerics get all spells) and i get my "mystery/archetype" spells for oracle but don't get to choose any beyond first level unless i choose oracle as my primary

**Comment by ArcaneTrixter** [comment]
This should finally be resolved in the linked preview build in the discord or the next published nexus build.
