### ISSUE TITLE
Request: Respec compatibility

### ISSUE THREAD

**Issue by Skarm-Ghelmaad** [cabarius/ToyBox#209]
I am trying to use this mod:

https://github.com/BarleyFlour/RespecMod

It allows to Respec characters, but it seems to be incompatible with Gestalt characters...

Would be possible to make a Respec mod compatible version or to integrate Respec feature in the mod?

Thanks,
Aghnaar/Skarm

**Comment by EnderWiggin** [comment]
How is it incompatible with gestalt? I've gestalted all my companions by respeccing through that mod.

**Comment by Skarm-Ghelmaad** [comment]
I am trying to restart the game with the fresh mods and no mod who could screw up (i.e. Respec, Fast Travel, etc...)...
