### ISSUE TITLE
Request: Mythic Spellbook Caster Level

### ISSUE THREAD

**Issue by codetmrrw** [cabarius/ToyBox#218]
Right now it's possible to add any spellbook to any character, and while normal classes function as expected mythic spellbook cannot gain any level and are thus useless to add, they seems strongly tied with the mythic class.

I would like to request the possibility to add level to those spellbook just like the standard ones, as to cast the unique spells attached to it

**Comment by ArcaneTrixter** [comment]
Should be resolved in 1.3.7 😺
