### ISSUE TITLE
Bug (probably): Adding or removing spells from any spellbook will remove or add them to all spellbook

### ISSUE THREAD

**Issue by codetmrrw** [cabarius/ToyBox#220]
It's already possible to add or remove any valid spells from any compatible spellbook, but if the character posses more then one spellbook and a particular spell is available for both, using this tool to add or remove them Will Add/Remove the selected spell from All compatible books, not just the selected one.

**Comment by ArcaneTrixter** [comment]
This should be resolved with the enhancement to the spell editor tab. Give it a try!
