### ISSUE TITLE
Request: Two-Handed Melee Spell Combat Cheat

### ISSUE THREAD

**Issue by LaViaa** [cabarius/ToyBox#225]

**Comment by LaViaa** [comment]
Essentially remove the free hand requirement in a similar fashion to the kineticist cheats?  Allowing for two-handed + dual-wield builds.

**Comment by Amariithynar** [comment]
Two-handed should already be able to do this just fine, given that you can one-hand the weapon temporarily to cast without issue? I also have no problem with my Woljif casting while dual-wielding.
