### ISSUE TITLE
Feature: Add of Parameterized Mythic Feats via Search n Pick

### ISSUE THREAD

**Issue by ESattler** [cabarius/ToyBox#227]
For Search n Pick, there is `ImprovedCriticalMythicFeat` but I don't see how to get it for a specific weapon type. This seems to be the case for
```
Improved Critical (Mythic)
School Mastery (Mythic)
Spell Focus (Mythic)
Weapon Focus (Mythic)
Weapon Specialization (Mythic)
```
where there isn't individual ones for each option. Where as regular `WeaponFocus` there is the option for every weapon type

**Comment by cabarius** [comment]
Does this work in 1.3.4?

**Comment by ArcaneTrixter** [comment]
This should be resolved. If you continue to have issues reopen this :)
