### ISSUE TITLE
Bug: Teleport Hotkey Appears To Bleed Through Bug Report Window

### ISSUE THREAD

**Issue by Racoras** [cabarius/ToyBox#237]
Series of bugs occured using Toybox 1.3.2. On area transition from interior cell (Drezen Barracks) to exterior (main siege fight), controlled Animate-Dead skeletons were located in a distant part of the map rather than near player party.  Possibly unrelated to main bug but added for full info. Turn based mode active, bugs occured during fight. 

Main bug occured when submitting report to Owlcat with in-game interface,  on three back to back occasions one of the characters (first Main Character, on skeleton's turn, then Camellia on her own) teleported to another location on the exterior map upon closing bug report window. Suspect the comma  hotkey may be taking effect to teleport them to mouse/camera location even while that textbox is active.

**Comment by cabarius** [comment]
resolved in 1.3.4
