### ISSUE TITLE
Newer Versions does not allow for pets or not in party teammates to be affected by feat multiplier

### ISSUE THREAD

**Issue by GioGr** [cabarius/ToyBox#242]
**Describe the bug**
Newer Versions does not allow for pets or not in party teammates to be affected by feat multiplier

**To Reproduce**
Go to Drezen 
have a pet ( mythic pet was fine, hunter pet was not) or a teammate to level ready
put feat multiplier above 1, and level said pet or teammate outside of party 

**Expected behavior**
As before this should allow pets or teammates outisde party while in town to be affected by feat multiplier

**Save Files**
[Manual_42_Instant_Events_Save.zip](https://github.com/cabarius/ToyBox/files/7176510/Manual_42_Instant_Events_Save.zip)

**Screenshots**

**Settings**
[Settings.zip](https://github.com/cabarius/ToyBox/files/7176512/Settings.zip)

**Version Info:**
 - ToyBox Version: 1.3.4
 - Game: 1.0.2g

**Additional context**
will try earlier versions to see when it happened

**Comment by cabarius** [comment]
What other mods do you have installed.  I can't load your save.

**Comment by GioGr** [comment]
> What other mods do you have installed. I can't load your save.

![image](https://user-images.githubusercontent.com/12425911/133599412-f1e9de1d-afe1-43ea-a798-3421138ada6b.png)

**Comment by cabarius** [comment]
please verify on 1.3.5

**Comment by GioGr** [comment]
Out of town, will try with anydesk if possible or else Monday
Thank you for quick fix <3

**Comment by cabarius** [comment]
Fixed in 1.3.5

**Comment by GioGr** [comment]
Yes working on 1.3.6
Thank you
