### ISSUE TITLE
Turn Based Combat is Broken (verify that it isn't all combat)

### ISSUE THREAD

**Issue by cabarius** [cabarius/ToyBox#26]
From the forums.

Hmm, when I engage in combat, my characters can't do any attack action - it works fine when I roll back to 1.06 - not sure what causes this. :/

**Comment by cabarius** [comment]
I suspect one of my ported patches from bag of tricks is the likely culprit.  I'll look into this ASAP

**Comment by Vek17** [comment]
This appears to be all combat as I was getting this in RtwP as well

**Comment by cabarius** [comment]
fixed in 1.1.2
