### ISSUE TITLE
Request: Arcane Spells addable to Divine Spellbook

### ISSUE THREAD

**Issue by novacor** [cabarius/ToyBox#260]
My favorite divine caster is oracle. Would love to have the ability to add arcane spells to an oracle spellbook as a revelation.

There are classes which specialize in this: Elf Ancient Lorekeeper can pick 9 wizard spells from the full wizard spellbook along with the oracle divine spellbook plus his mysteries. Until Owlcat fixes the broken Loremaster prestige class I really would rather wait to play my fav class here. Any ideas?

https://www.d20pfsrd.com/races/core-races/elf/ancient-lorekeeper-oracle-elf

**Comment by ArcaneTrixter** [comment]
While Toybox is not in the business of adding blueprints, prestige classes, or other permanent changes, you can now modify your spellbook to add spells from any caster type to the oracle spell list in the Party Editor.

**Comment by novacor** [comment]
Much thanks to you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
