### ISSUE TITLE
Request: Allow character to get experience past level 20

### ISSUE THREAD

**Issue by Zentsuki** [cabarius/ToyBox#261]
It would be useful for parties of less than 6 with exp share off, or better yet, for a solo character. The Legend mythic path allows you to progress up to level 40 (but still cap any single class to 20) with vastly increased experience, so what if other mythic paths had the same ability without the increased exp rate? 

That way, a solo character could realistically beat the game on their own without having to use gestalt classes, or "cheating" by always allowing level-ups but rather earn their levels.

**Comment by ArcaneTrixter** [comment]
Adding the level 40 without the "increased experience rate" would take adding a new blueprint for experience table and likely needs to be its own, different, mod. I've added the "fake legendary hero" toggles to let any character level to 40, but they will use the Legend experience tables and level faster than a normal character. 

I'd suggest asking in the discord if anyone is interested or able to create such a mod if there isn't one already.
