### ISSUE TITLE
Can't modify stats on other characters

### ISSUE THREAD

**Issue by cabarius** [cabarius/ToyBox#28]

**Comment by cabarius** [comment]
From the boards:
Another error, this one rather more major - in Party Editor, when clicking on the Stats, Facts, etc. arrow for party members, the corresponding function for the PC opens instead, so we can't modify anything in the Party Editor for other party members.

**Comment by tanllwyth01** [comment]
The modifications are possible, but only if you move the members around. For example, on the active companion tab, I had Seelah, Cam, Lann, and Wendy in order to edit Lann I had to move him to the position Seelah had in the party then it worked.
