### ISSUE TITLE
Main character restart on gestalt loaded save

### ISSUE THREAD

**Issue by Strange09** [cabarius/ToyBox#281]
Whenever you load a file with a gestalted main character, it forces you to go through character creation again, giving infinite extra levels.

In order to reproduce the bug, just loading a save with a Gestalt character should do the trick.

Hopefully, a good fix should keep the stats from the saved file when you load it instead of restarting the entire character creation process.

 - ToyBox Version: [1.3.6]
 - OS: [Windows 10]

**Additional context**
Going to "Party", then resetting character level seems to fix the unintended behaviour. However, this seems to cause hit point loss.

[Manual_57_gestaltsav.zip](https://github.com/cabarius/ToyBox/files/7193085/Manual_57_gestaltsav.zip)

**Comment by ArcaneTrixter** [comment]
Can you also add your settings for this? This sounds like what happens when you incorrectly set up gestalt.

**Comment by ArcaneTrixter** [comment]
This is because of incorrectly having both classes flagged as gestalt. I'm adding a fix in #416 to prevent that from happening, and I've added a button to recover from this.
