### ISSUE TITLE
Request: "Guys, don't leave me" button

### ISSUE THREAD

**Issue by Rosterius** [cabarius/ToyBox#291]
Would it be possible to remove flags that cause automatic departure of some companions when you choose some specific mythic paths? (It was EXTREMELY irritating when Arueshalae left me after I chose demon mythic path.)

If something like this is too complicated, how about a button that adds/return specific companions to party roster?
It can't be that hard, and I'm sure a lot of people would appreciate it.

**Comment by Amariithynar** [comment]
You can corrupt her to keep her as Demon Path, FYI. She'll be re-recruitable in the next act as a full-fledged succubi.

<details>
  <summary>Spoiler warning</summary>

 You can corrupt her to keep her as Demon Path, FYI. She'll be re-recruitable in the next act as a full-fledged succubi. 

</details>

**Comment by Amariithynar** [comment]
<details>
  <summary>Spoiler warning! There is a way.</summary>

 You can corrupt her to keep her as Demon Path, FYI. She'll be re-recruitable in the next act as a full-fledged succubi. 

</details>

**Comment by Rosterius** [comment]
Yes, I know about that.
I also know, that corrupted Arueshalae is not romanceable and she is an absolutely terrible companion.
Terrible class progression, terrible feat and terrible mythic abilites.
And she can not be respect...

But this is not only about Arueshalae.
I think it's also a good thing for people who want to test some companions without having to start a brand new game with a different mythic path.

**Comment by Truinto** [comment]
Already figured out how to do this feature. Will make a pull request tomorrow afternoon.

**Comment by Amariithynar** [comment]
> But this is not only about Arueshalae.
> I think it's also a good thing for people who want to test some companions without having to start a brand new game with a different mythic path.

Oh I agree wholeheartedly. I just wanted to provide some slight help in case you didn't know.

**Comment by Rosterius** [comment]
> 
> 
> Already figured out how to do this feature. Will make a pull request tomorrow afternoon.

BTW, I am that guy from discord :-)
Name Edvin was already taken on this forum.

I am happy to inform you that everything works. 
Romance, quests, interactions, everything is completely without problems.
