### ISSUE TITLE
Could casterlevels (and their spellbook access) be changed separately from character levels?

### ISSUE THREAD

**Issue by cabarius** [cabarius/ToyBox#30]
Could casterlevels (and their spellbook access) be changed separately from character levels?
Semi-gestalt chars aside, having that option might work as a quick&dirty fix for the >20 casterlevel bug that merged mythspellbooks cause right now.

**Comment by cabarius** [comment]
I added the ability to edit character level and class level.  I attempted to add the ability to level up the caster level of your spellbook but there are various issues with the game that make this more complicated.  Basically it increases the level and if you add spells you can not see them until you level up high enough.  This needs further investigation.

**Comment by ArcaneTrixter** [comment]
This is done, although I have more enhancements I still to do in that space.
