### ISSUE TITLE
Feat multiplier breaks Aivu/Skeletal Companion

### ISSUE THREAD

**Issue by Nerin3** [cabarius/ToyBox#304]
After some testing, I noticed that when you enable Feat Multiplier, it breaks the companions from mythic paths (Aivu and Skeletal companion)

Using feat multiplier at rank 3rd rank lvlup reduces their hp to 1/1 and spawns them without a class.

**Comment by Rudm0909** [comment]
Also got this bug if you have it just respec your mythic path using a mod (Not the games respec) and dont use feat multiplier after the 3rd mythical level or the companion will not level up (in my case Aivu)
