### ISSUE TITLE
Request: Mystic Spells Absent Even When Selecting The "Search All Spellbook Option" Is Active

### ISSUE THREAD

**Issue by codetmrrw** [cabarius/ToyBox#313]
Recently a new feature allow for a far better management of spellbooks in the game by allowing to add any "normal" spell to any spellbook, however unique Mythic Spells (Demon, Angel, etc.) are unavailable even with this option selected.

I request the possibility to include this unique spells to the selection.

**Comment by ArcaneTrixter** [comment]
Resolved in upcoming 1.3.9 :)
