### ISSUE TITLE
Legendary Hero flag gives huge amount EXP after level up

### ISSUE THREAD

**Issue by Bregoran** [cabarius/ToyBox#315]
Hi, after using the "Levels like a Legendary Hero" flag in the new 1.3.8 Tobox version and playing with 0.1 EXP multiplier i get a huge amount of exp after a level up and can instantly level up again.

![Screenshot 2021-09-23 172830](https://user-images.githubusercontent.com/40921742/134537163-e316f4cf-12c5-48f3-8e37-2c773091066b.png)

Level up in Toy Box 1.3.7 worked without a problem with the old toggle, the game stayed on the current exp and didnt increased it but this was before i reached level 20, maybe the bug would happen in 1.3.7 too.

With the new version  the exp bugs happens after level 20
![Screenshot 2021-09-23 174958](https://user-images.githubusercontent.com/40921742/134540810-6b4191e2-5a31-4145-b763-de86a6fefcee.png)
![Screenshot 2021-09-23 175250](https://user-images.githubusercontent.com/40921742/134541336-49dc75c0-5e0e-41ec-8bca-e2c5df7072be.png)

**Comment by ArcaneTrixter** [comment]
This is going to require some fixing so that it doesn't break the same effect which is *supposed* to happen for actual Legendary Heroes getting a bunch of levelups when you get it.
