### ISSUE TITLE
At-Will Toggle

### ISSUE THREAD

**Issue by InfinityArts9o** [cabarius/ToyBox#322]
Version 1.3.7 had an option to make a spell in the spellbook an at-will SLA, it appears this function is no longer available in 1.3.8.  Please restore that functionality.

Spellbook rework is amazing, though.  Now I can finally make Ember the angel she truly is.

**Comment by ArcaneTrixter** [comment]
That functionality is on the search n' pick menu for adding spells that aren't tied to a spellbook.
