### ISSUE TITLE
Mythic Paths Spell can't be removed as an at-will ability

### ISSUE THREAD

**Issue by tassadarpaladin** [cabarius/ToyBox#323]
**Describe the bug**
In Search'n Pick Function, you can see both "add" and "at-will" buttons after searching for any spells from Mythic Path if you have any spell books.

The Mythic Path Spell can't be add to any regular spell books, clicking "add" nothing happens.

Another problem is: If you add Mythic Path Spell as an at-will ability, you can't remove it. Before 1.3.8 there was an "remove" button after adding any spell as ability. Now it's empty as screenshot shows. In Party-Character-Ability section there is also no "remove" button.

**Expected behavior**
The Mythic Path Spell should be able to be removed from abilities.

**Screenshots**
![1](https://user-images.githubusercontent.com/10878147/134614716-7284c682-d064-463d-8388-ac0ed5674835.png)
![2](https://user-images.githubusercontent.com/10878147/134614732-0ce64e36-7bc5-4944-a310-89c6bd9f7bb8.png)

**Version Info:**
 - ToyBox Version: 1.3.8

**Comment by ArcaneTrixter** [comment]
Yeah, the add button shouldn't be showing up at all on the Search n' Pick screen. I'll look.
