### ISSUE TITLE
Gestalt: "Largest" Skill point growth option is identical to "Sum"

### ISSUE THREAD

**Issue by RendonGH** [cabarius/ToyBox#324]
Presently, if I select the "Largest" option for skill point growth, the number of skill points I receive is identical to Sum.
My understanding of the Gestalt ruleset is that the "Largest" option should give you the skill point growth that is the highest of your gestalt classes. ie: If a Bard gets 6+ int modifier, and a Wizard gets 2+ in modifier, a Gestalt Bard/Wizard will get 6 skill points + int modifier per level. What happens in game is that I get 8+ int modifier skill points, resulting in some ludicrous skilling going on.

**Comment by Deltharis** [comment]
Should be fixed in 1.3.10
