### ISSUE TITLE
Parameterized Features (Normal and Mythic)

### ISSUE THREAD

**Issue by Dimensionist29101991** [cabarius/ToyBox#33]
The current Search n Pick system does not account for adding parameterized features the way they're normally done in the game. This means that the game does not register those feats as being added, and will not allow you to choose feats which have those as prerequisites while leveling up. It's also pretty annoying for those who have OCD.

Anyway, a separate tab for parameterized features might help, like there is in Bag of Tricks.

**Comment by ArcaneTrixter** [comment]
Done!
