### ISSUE TITLE
1.3.10 Mythic Spellbook Error

### ISSUE THREAD

**Issue by InfinityArts9o** [cabarius/ToyBox#338]
**Describe the bug**
Running into an exception when trying to access the spells tab of a Magus 10, Lich 10 main character.  Lich spellbook added via Toy Box 1.3.9 and was able to edit with that version with no issues.

Able to access Paladin 10 (CL 7) Seelah's spellbook as normal.

**To Reproduce**
1. Load game
2. Open Toybox via mod manager
3. Go to Party Tab
4. Open Spells submenu on referenced character
5. Encounter unresettable error
6. Make bug report and revert to 1.3.9 to keep cheat- playing

**Expected behavior**
Spellbook menu loads as normal.

**Save Files**
[Quick_8.zip](https://github.com/cabarius/ToyBox/files/7229930/Quick_8.zip)
Running a number of other mods, I believe Tabletop Tweaks 1.3.0 is the only other one required to load the save.

**Screenshots**
![image](https://user-images.githubusercontent.com/23132232/134776046-9409c385-8a80-41ef-a918-fe2a97f42a46.png)

**Settings**
[Settings.zip](https://github.com/cabarius/ToyBox/files/7229938/Settings.zip)

**Version Info:**
 - ToyBox Version: [e.g. 1.3.10]

**Additional context**
N/A

**Comment by ArcaneTrixter** [comment]
Thanks! Should be fixed ASAP!
