### ISSUE TITLE
Toybox being enabled prevents ability resource usage regardless of settings.

### ISSUE THREAD

**Issue by Vek17** [cabarius/ToyBox#34]
On ability activation no rounds are consumed from Bard or Azata songs. This is also true of subsequent rounds. This was observed with no flags enabled, and when I disabled Toybox and Restarted the game did not occur. Enabling Toy box immediately breaks the expected behavior. This was tested with 1.1.2

**Comment by cabarius** [comment]
Fixed in 1.1.3
