### ISSUE TITLE
Caster Level increases to much on level up with Prestige Class "Mystic Theurge" with feat selection multiplier

### ISSUE THREAD

**Issue by revan2811** [cabarius/ToyBox#343]
**Describe the bug**
When picking Mystic Theurge for the first time with feat selection multiplier 4 enabled, the caster level of the divine caster class you pick increases by 4.

**To Reproduce**
1. have feat multiplier on anything above 1
2. pick Mystic Theurge for the 1st time and pick 1 arcane caster class (leaving the other 3 blank) and 1 divine caster class (leaving the others blank again)
3. finish level up
4. if you look in your spellbook the arcane caster class has increased by 1 (correct) the divine caster class has increased by 4

**Expected behavior**
divine caster class should also just increase by 1

**Settings**
Please attach your settings.xml file from the mod folder
[Settings.zip](https://github.com/cabarius/ToyBox/files/7230369/Settings.zip)

**Version Info:**
 - ToyBox Version: [e.g. 1.3.9]

**Comment by Amariithynar** [comment]
Would request that you modify the title to include "with feat selection multiplier" for greater clarity; it doesn't happen without it, after all!

**Comment by Amariithynar** [comment]
Would request that you modify the title to include "with feat selection multiplier" for greater clarity; it doesn't happen without it, after all!

**Comment by revan2811** [comment]
Alright I changed the title. It is however no longer needed,
Tested again with the new version 1.3.12
The problem is gone now.
So thanks. Case closed.
