### ISSUE TITLE
Spell Addition Through Party Editor Is Bugged

### ISSUE THREAD

**Issue by Dimensionist29101991** [cabarius/ToyBox#35]
Using the spell editor in Party Editor, you can only make the level 9 spells of a character's spellbook At Will abilities, you can't add them to the spellbook normally.

**Comment by Dimensionist29101991** [comment]
In addition, not sure if this is related or not, but after adding spells to a character through the Party Editor, my character now has only three level 8 spells occupying every level slot (she's a spontaneous caster).

**Comment by cabarius** [comment]
Fixed various issues with spell editing in 1.1.13.  Please file a new bug for new issues found.
