### ISSUE TITLE
woljif is now the protagonist.

### ISSUE THREAD

**Issue by OldBluntman** [cabarius/ToyBox#357]
**Describe the bug**
woljif is now the protagonist. After walking through the market square with him in a party, he begins to respond to all dialogues as the main character of the game, and upon returning to the tavern, the game is tightly blocked. When you try to change the composition of the squad on the world map, the lock icon weighs on woljif, but not on the main character. 

The bug occurs only if you save and load on the market square with woljif in the party and with generalstalt classes for him and for the main character.

Ver 1.3.13.1 (Toy Box), 1.0.6d (gog)

**Comment by mindcloud69** [comment]
So I ran into this. Use [Arcemi Pathfinder WotR Save Editor](https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/91) to reset your character back to the main char. [They added](https://github.com/jaygumji/ArcemiPathfinderKingmakerTools/issues/6) the feature when I ran into this issue. I find that if you are not actively leveling up turning off the gestalt check box prevents a lot of issues.

**Comment by zei147** [comment]
I had this happen when I mistakenly had all his classes checked as Gestalt which sets his level to 0 on a reload. If you then try to level him up when his level is 0, is makes him party leader (or anyone else for that matter). To avoid, only set one of his classes as gestalt (assuming 2 classes total). This avoids the mod from calculating his character level as 0 and the subsequent issues that result. It's possible you may be running into a different issue, but I wanted to put this here in case it helps.

**Comment by mindcloud69** [comment]
So Have I been doing this wrong the whole time? You only select the checkbox for second class for gestalt and the select the primary on level up?

**Comment by zei147** [comment]
Yes, if you select both classes as Gestalt, it will not count either of them toward you character level, which results in character level 0 and all sorts of issues can come out of that.

**Comment by ArcaneTrixter** [comment]
I've added a button to enable you to restore your main character to the correct character, and also set up something to make it more difficult to cause this scenario. Should be resolved by #416
