### ISSUE TITLE
Adding Character to Party Generates Dummy Level 0 Character

### ISSUE THREAD

**Issue by InfinityArts9o** [cabarius/ToyBox#361]
**Describe the bug**
Adding a party member that is not in the party to the party adds a level 0 dummy version of them instead of the character.  This dummy can be removed and the real character be added.  Attempting to level this dummy creates a new protagonist and turns the existing protagonist into a mercenary.

**To Reproduce**
1. Launch game & load save
2. Go to Party Tab
3. Attempt to add a party member that's not in the party to the party
4. Note dummy level 0 version is added
5. Remove dummy and add real character

**Expected behavior**
Adding a party member adds the real version of them and not a dummy.

**Save Files**
[Manual_181_Scrubland_by_a_Bend_in_the_River__12_Lamashan__X__4715__00_47_06.zip](https://github.com/cabarius/ToyBox/files/7248005/Manual_181_Scrubland_by_a_Bend_in_the_River__12_Lamashan__X__4715__00_47_06.zip)
Running Tabletop Tweaks and a bunch of other mods.  TT is required to load save.

**Screenshots**
![image](https://user-images.githubusercontent.com/23132232/135182660-7e7adfab-eb7a-481b-ae8c-932258339409.png)
![image](https://user-images.githubusercontent.com/23132232/135182682-2b6cdf7a-2625-44d8-ad0a-665fcf74a835.png)

**Settings**
[Settings.zip](https://github.com/cabarius/ToyBox/files/7248000/Settings.zip)

**Version Info:**
 - ToyBox Version: [e.g. 1.3.13.1]

**Additional context**
The dummy character allows access to locations that require that party member (i.e. for quest locales).  The dummy is uninteractable and will result in a stuck quest if the character is required in a dialogue to resolve the step.

**Comment by Dekent59** [comment]
I had the same issue, I rolled back to 1.3.12 and it works fine.

**Comment by cabarius** [comment]
resolved in 1.3.14
