### ISSUE TITLE
Belt Items Disappearing when acquiring mythic rank 4

### ISSUE THREAD

**Issue by Ebonmark** [cabarius/ToyBox#363]
**Describe the bug**
With the 'Refill Consumables in Belt Slot' option checked off, upon gaining Mythic Rank 4 in a certain someone's lab, 4 of my 5 belt items got deleted. (2 wands, tricertops statue and the inheritor belt buckle thing).

**To Reproduce**
With the 'Refill Consumables in Belt Slot' option checked off, have a variety of belt items equipped to the main character and interact with the lexicon at the end of Areelu's lab.

**Expected behavior**
After the cutscene, your ingame belt items will be missing.

**Save Files**
-

**Screenshots**
-

**Settings**
Please attach your settings.xml file from the mod folder

**Version Info:**
 - ToyBox Version: [1.3.8]

**Additional context**
-

**Comment by cabarius** [comment]
Please verify this on 1.3.16.  I fixed an issue there.
