### ISSUE TITLE
Enchantment "Tweaking"

### ISSUE THREAD

**Issue by Skarm-Ghelmaad** [cabarius/ToyBox#368]
SOLUTION
Would be possible to "tweak" an enchantments to allow for the following custom variants?

For example:
a) Meta-magic-altered spell activations (i.e., casting a quickened, extended, etc... spell effect).
b) Add an enchantment that changes the activation action (i.e., activate as a free, swift, move or full-round action instead of standard action).
c) Add a rule-based trigger that instantly auto-activates the selected effect either on the wearer, on the attacker or on an area centered on them based on a set of simple conditions (i.e., when struck in combat, when striking in combat, when causing a critical in combat, when the wearer's hit points drop below a certain threshold [i.e., 25%, 50%, 75% or 100%], when the struck opponent's 's hit points drop below a certain threshold [i.e., 25%, 50%, 75% or 100%], when the wearer or the stuck opponent is dying or dies, when combat starts, when an enemy is in sight, etc... in fact, further ideas could be taken from the auto-pause triggers of the game itself...). 

FURTHER ENHANCEMENTS
- The rule-based triggering could be associated with a specific DC of a specific skill check, which would be auto-rolled.
- The rule-based trigger could strict the targeting of the effect on attackers, struck opponents or wearers with a specific class, Mythic path, alignment, creature type or subtype, a certain character or class level, class feature or ranks in a specific skill.

**Comment by Rudm0909** [comment]
These are some great ideas i support it!

**Comment by Truinto** [comment]
I don't want to be pessimistic, but that are content based suggestions. Which clearly goes against the spirit of Toybox. In short it would generate blueprints that make it impossible to uninstalled the mod from your save. Also mixing triggers with effects sounds very difficult. Not impossible, but I wouldn't know where to start. I think it would probably just as effective to build a few cool combinations and call it a day.

Btw, applying existing enchantments is already possible. So maybe there is already an enchantment for what you want.

**Comment by ArcaneTrixter** [comment]
As Truinto said, Toybox does not add blueprints which means that almost all of these are not feasible in this mod. It would certainly be a neat mod though!

**Comment by Skarm-Ghelmaad** [comment]
> I don't want to be pessimistic, but that are content based suggestions. Which clearly goes against the spirit of Toybox. In short it would generate blueprints that make it impossible to uninstalled the mod from your save. Also mixing triggers with effects sounds very difficult. Not impossible, but I wouldn't know where to start. I think it would probably just as effective to build a few cool combinations and call it a day.

I understand...
Yeah...honestly mine was just a random suggestion by someone who really has no clue how to **seriously** mod this game (apart from making custom portraits... :O )...so well...thank you for getting back on me and for clarifying why wouldn't be coherent with the Toybox philosophy...
