### ISSUE TITLE
Toybox breaks Metamagic spell creation

### ISSUE THREAD

**Issue by Vek17** [cabarius/ToyBox#37]
While toybox is enabled it is impossible to create new metamagic spells in a spellbook as the book will report that you have no metamagic feats regardless of actual feats possessed.

This was observed with the 1.1.4 release build on nexus.

**Comment by cabarius** [comment]
Fixed in 1.1.5

**Comment by cabarius** [comment]
This  one was weird because I had fixed it for 1.1.0 but somehow reverted the fix.
