### ISSUE TITLE
FLAGs are gone?

### ISSUE THREAD

**Issue by Knucklehead312** [cabarius/ToyBox#371]
I am currently trying to change the outcome of Prisoner of the Abyss so I can recruit Trever into my party, unfortunately I didn't choose the correct dialogue options and I downloaded this mod to fix it. Supposedly there are supposed to be FLAGs regarding a victim, hero, and traitor counter when I search up Sosiel in the search n find tab. I cannot find the FLAGs tab, and when I find the blueprints for each of the counters I cannot edit them in any way.

**To Reproduce**
1. CTRL-F10
2. Select Search N Find
3. Select Sosiel
4. Type Sosiel in the search box
5. Scroll down to the Sosiel_Victim blueprint

**Expected behavior**
I believe there is supposed to be a flags tab that I can open and use to unlock the counter so that I may edit it

**Version Info:**
 - ToyBox Version: 1.3.15

**Comment by cabarius** [comment]
Go to Search 'n Pick and choose Flags and search for it like this 
![image](https://user-images.githubusercontent.com/331144/135411603-095ef50e-9810-4098-adfc-b400e19ef125.png)
