### ISSUE TITLE
ToyBox Breaks Seelah's Wedding Quest with an Ability Blueprint Error

### ISSUE THREAD

**Issue by INovemI** [cabarius/ToyBox#374]
Seelah's chapter 3 wedding quest sends you back to the main menu after talking with Arsinoe to start the ceremony.

**Comment by cabarius** [comment]
I fixed a crash which I introduced in 1.3.15 when fixing the refill belt issue.  Please verify in the next release (either 1.3.15.1 or 1.3.16)

**Comment by INovemI** [comment]
Fixed.
