### ISSUE TITLE
Legend XP Level UP issue

### ISSUE THREAD

**Issue by solo16** [cabarius/ToyBox#378]
Allow LV past 20 is unchecked but after adding the legend feature it still give me excessive experience. It was working properly with the game 1.07e but since the 1.07f (just updated about 10 mins ago) it doesn't work again.

Thx!

**Comment by ArcaneTrixter** [comment]
Can you explain more specifically (e.g. at level x with y experience, I level up. I now am level x+1, and have z experience) or provide a save and settings where this happens? I've just tried it with the latest patch on my test legend save with the pinned experimental build and it doesn't appear to give extra experience?

**Comment by solo16** [comment]
Sure, like before the patch when I added the legend feature which give me a stat +4 boost without the excessive experience e.g. I'm currently at level 14 which has 627668/635000 exp but once I selected the feat my exp is now 627668/105000 which I presume it will allows me to lv beyond LV20 which also mean the checkbox under the character tab Allow Level Past 20 nullified.

My idea is to take that feat without leveling past 20 at least not too early I wish to have more control on leveling past that at later chapter.

Hope this help explaining the issue

Thanks you so much!

**Comment by ArcaneTrixter** [comment]
Okay, cool. So this is just not understanding what Legend does. It doesn't just let you continue going to 40, it reduces the experience you need (by a huge amount) in order to level. Both the legendary flag and the real Legend feat do that.

**Comment by solo16** [comment]
Cool thx a lot ! Understood now.
