### ISSUE TITLE
Can't merge spellbooks for Mythic paths outside of Arcane/Lich and Divine/Angel

### ISSUE THREAD

**Issue by Lord451125** [cabarius/ToyBox#398]
Tested with multiple classes, spell books don't seem to be mergeable outside of the ones already included as base.  

If this is something to toggle I might be missing it but searched through each tab line by line and couldn't find it.

**Comment by ArcaneTrixter** [comment]
You can only merge spellbooks for which you have actual class levels. Check under Party Editor -> Spells for any spellbooks which otherwise meet the criteria.

**Comment by Lord451125** [comment]
Ohh, I see now.  The problem I was having is I didn't go far enough into the process and merge them after having selected the mythic class.  Thank you.  

I was testing it by rerolling a high level character (who already had lich merged) so I didn't go far enough.  For anybody else whos tumbles on this, once you select the mythic class you then have the option of merging the spell book.  

Much appreciated.
