### ISSUE TITLE
Mercenaries point buy uses MC value.

### ISSUE THREAD

**Issue by jpbogossian** [cabarius/ToyBox#41]
Trying to hire a Mercenary in Defender's Heart, it has 25 point when should have 20. It is following the value for the Main Character point buy instead of Mercenary.

[Manual_151_Mercenary.zip](https://github.com/cabarius/ToyBox/files/6270450/Manual_151_Mercenary.zip)

**Comment by cabarius** [comment]
Fixed in 1.1.8

**Comment by killslash** [comment]
@cabarius I am getting this issue in the latest version 1.4.1.3
