### ISSUE TITLE
Add either "Party can move through each other" or "Party hitbox modifier" *Enhancement*

### ISSUE THREAD

**Issue by ooblagis** [cabarius/ToyBox#42]
Like in the old Turn-Based mod, to avoid the endless nightmare of hallway traffic jams.

**Comment by cabarius** [comment]
Can you give me a save that reproduces a hallway traffic jam?  I implemented this and after spending some time testing I couldn't observe blockages even with all mods uninstalled

**Comment by cabarius** [comment]
I went back to Kingmaker and also observed my characters able to run through others in the party.

**Comment by ooblagis** [comment]
Posted save on Discord

**Comment by cabarius** [comment]
I love your save.
Fixed in 1.1.9
