### ISSUE TITLE
Add Finance/Materials/Divine Points, for the Crusade portion of the game (Also, army recruitment)

### ISSUE THREAD

**Issue by Dimensionist29101991** [cabarius/ToyBox#43]
As it says in the title, an option to add resource points for the crusade would be good. Finance and Materials can be handled via money, but Divine Points cannot.

Perhaps more useful would be either changing the rate at which armies populate per week, or allowing direct editing of existing legions. Generals too.

**Comment by ArcaneTrixter** [comment]
I believe this is all resolved at this point, although there will continue to be enhancements around editing generals and armies.
