### ISSUE TITLE
[Request] - Enchantment : Rename items

### ISSUE THREAD

**Issue by UniKhorne** [cabarius/ToyBox#436]
Adding an option in [Enchantment] to give a custom name to an item when editing enchantments of said item.

Example:

- Add [Rapier +1] to inventory
- Add [Flaming] to [Rapier +1]
- Rename [Rapier +1] into [Flaming Rapier of Camellia]

Other example, RobRendell's Craft Magic Items mod from Kingmaker
![image](https://user-images.githubusercontent.com/89249782/136374459-df6881f9-1f36-4527-934e-401c84db0e2a.png)

**Comment by Valdacil** [comment]
+1
