### ISSUE TITLE
Aeon unlock don't work, if way locked in Gray Garrison

### ISSUE THREAD

**Issue by Antigus** [cabarius/ToyBox#437]
**Describe the bug**
Aeon unlock don't work, if this way locked in Gray Garrison (any not-aeon choise)
**To Reproduce**
1. Go to 'level up tab'
2. Click on 'unlock Aeon'
4. Mythic way of Aeon is locked

**Settings**
default settings

**Version Info:**
 - ToyBox Version: [e.g. 1.3.18]
 - OS: Win10

**Comment by fikrivoxel** [comment]
you can unlock aeon in level 3 mystic path and in garay garrison is level 1

**Comment by Antigus** [comment]
i'm select "good" way in garrison and now Aeon dissapear from my mythic selection tab.

**Comment by RuiyuZhu** [comment]
Same for Lich.
