### ISSUE TITLE
Swarm Size Enhancement Request

### ISSUE THREAD

**Issue by 359763432** [cabarius/ToyBox#442]
I really would like to have an enhancement on the swarm size as a swarm-that-walks player! As it is the core value number for many swarm abilities involved.

![](https://cdn.discordapp.com/attachments/815735034514112512/896025850053529600/unknown.png)
![](https://cdn.discordapp.com/attachments/815735034514112512/896030765509382215/unknown.png)

**Comment by riggs** [comment]
Bumping this. In `party.json`, the entry is:
```
"$type": "Kingmaker.UnitLogic.Parts.UnitPartLocustSwarm, Assembly-CSharp",
"CurrentStrength": 22097,
"CurrentScale": 20
```

**Comment by riggs** [comment]
Feature is still missing. Per further testing, setting this value in a save file works, but doesn't update all associated values until another corpse is consumed.

**Comment by riggs** [comment]
That works!
