### ISSUE TITLE
Gestalt -- sticky class bug

### ISSUE THREAD

**Issue by NordicRest** [cabarius/ToyBox#450]
**Describe the bug**
Woljif is getting levels in base Rogue, Fighter, and Alchemist, despite only having Fighter enabled as an additional level up class.

**To Reproduce**
(suspected)
1. Attempt to add an archetype of an extant class as a gestalt class (in this case, I added Knife Master as a gestalt while he had Eldritch Scoundrel levels). This crashes Toybox, but also marks the extant class as gestalt. I also had Vivisectionist Alchemist marked as an additional level up class at the time.
2. Respec the character, I was using Barley's respec mod. Possibly unnecessary, you may just need to take additional levels on the character.
3. Base Rogue and Alchemist were now gaining levels as additional level up classes despite not being marked as such in Toybox's settings.

**Expected behavior**
Rogue and Alchemist do not gain levels when not selected.

**Save Files**
[NordicRest-StickyClass.zip](https://github.com/cabarius/ToyBox/files/7316369/NordicRest-StickyClass.zip)

**Settings**
[Settings.zip](https://github.com/cabarius/ToyBox/files/7316370/Settings.zip)

**Version Info:**
 - ToyBox Version: 1.4.0
 - OS: Win10 v21H1
 - Version 1.0.8e

**Additional context**
Other mods in use at the time: 
Arcane Additions v0.2.1
Enchanced Inventory v1.0.5
MythicSpellbook Tweaks v3.1.0
Pathfinder Autobuff v0.1.5b
Respec Mod v1.6.6
Tabletop Tweaks 1.5.2
World Crawl v0.465

**Comment by Mira132** [comment]
It appears any classes that you gained level in and have marked as gestalt now level up no matter what. As you've mentioned, they should only level up if selected as additional classes per level, not just whether they are gestalt or not.
