### ISSUE TITLE
Feature Request: Fully respec NPC companions

### ISSUE THREAD

**Issue by Aephiex** [cabarius/ToyBox#461]
**Is your feature request related to a problem? Please describe.**
Some companions have inefficient attribute distributions, unwise feat picks, and classes that apparently better choices present, that they nearly drive me mad. While I can edit their stats easily, I still wish that I had an option to fully respec them and start over from level 0.

I do know that there is a respecialization mod, but it does not remove all facts and feats that should be when respec and sometimes it removes something that shouldn't be. As far as I know toy box respec use vanilla code and should be less buggy than that.

**Describe the solution you'd like**
Add another respec button for NPC companions only which sets their level to 0 and removes their classes, feats, and features, except for background and deity selection.

**Describe alternatives you've considered**
Or change the respec button itself.

**Additional context**
Nothing.

**Comment by Deltharis** [comment]
> As far as I know toy box respec use vanilla code and should be less buggy than that.
I doubt that, but maybe in some scenarios?

> Add another respec button for NPC companions only which sets their level to 0 and
Well, if we did that it wouldn't be vanilla respec would it?

As such I think you'll have better luck reporting bugs ("does not remove all facts and feats that should be when respec and sometimes it removes something that shouldn't be") to actual respec mod than hoping for toybox to replicate that but somehow do it better.
