### ISSUE TITLE
Increased buff duration affects Resurrection & "Summonappear" buffs

### ISSUE THREAD

**Issue by Ynead** [cabarius/ToyBox#471]
**Bug**
Increasing buff duration using ToyBox affects both **Resurrection** and **summon being unable to act during 1 round** even though it shouldn't. Furthermore, buff duration remains stuck at the new increased value even when trying to reset it back to 1. 

**To Reproduce**
1. Open the ToyBox interface
2. Increase buff duration to 999
3. Resurrect a party member or summon anything via scroll, ability, spell etc
4. See that both a completely unresponsive, can't be hit by anything and so on
5. Trying to set buff duration back to 1 doesn't work, it remains stuck at 999 even if it doesn't show on the interface.

**Expected behavior**
1. Buff duration shouldn't affect Resurrection and SummonAppear buffs. 
2. Resetting buff duration increase should actually reset it to 1, instead of remaining stuck.

**Settings**
Github doesn't support xml files. 

**Version Info:**
 - ToyBox Version: [e.g. 1.3.4]

**Additional information:** 

Summons not acting is caused by the following buff : "6179bbe7a7b4b674c813dedbca121799"  =  "SummonedUnitAppearBuff".

**Comment by caloyers** [comment]
Thanks for the reply, tried searching for it in exemptions but did not appear.
![image](https://user-images.githubusercontent.com/73109305/228528456-57119bff-fbcc-48e4-981c-4f0e996a0679.png)
