### ISSUE TITLE
Adjust/Unlimited Skill Points when creating character/levelling up

### ISSUE THREAD

**Issue by Zeruvi** [cabarius/ToyBox#474]
I assume this is already an available feature that I'm just completely missing, if so by all means call me an idiot and close this.
If it's not already a feature I'm amazed no one has requested it.

I would like to be able to adjust available skill points when creating character & leveling up, rather than having to manually edit the individual skill values for a character every level if I want them to stay consistent with my level. I like passing most skill checks but still have the chance of a rare failure.
This functionality existed in the Kingmaker Bag of Tricks - a tickbox labeled "infinite skill points". The note said it had to be disabled to progress level up but it actually worked when always checked.

Thank you very much for your effort and time to save us effort and time.

**Comment by Harry-894** [comment]
this should be labeled as a bug since the unlimited skill points exist but don't seem to work at all, however, the ignore skill caps work as intended.
