### ISSUE TITLE
Gestalt Levelling disconnected from spellbook

### ISSUE THREAD

**Issue by Vazre** [cabarius/ToyBox#484]
When levelling in Gestalt, a character with a spellbook (such as a Cleric / Inquisitor) levels their spellbook independently of their class- in order to set my inquisitor level to 2 in Neathholme, I set character level and cleric level to 1, then hit level up- This levels Cleric and Inquisitor both properly to 2, but your Cleric Spellbook will be level 3.

![image](https://user-images.githubusercontent.com/80865047/137637340-dd3514cb-a894-4d81-a715-ae9da9dcfe27.png)

**Settings**
Please attach your settings.xml file from the mod folder

**Version Info:**
 - ToyBox Version: [1.4.2]
 - OS: [Win10]
 - Version [1.0.9.c]

[Manual_34_Gestalt_Bug.zip](https://github.com/cabarius/ToyBox/files/7360466/Manual_34_Gestalt_Bug.zip)
.

**Comment by Vazre** [comment]
Pictured here is my attempts to fix this error by setting my cleric level back to 2, only for it to happen again, raising inquisitor and cleric's spellbook levels again without raising my actual level.

**Comment by semiliterate** [comment]
every time you level up via the level up interface, the game will increment your spellcasting level. For this reason, you cannot take two level twos like this without increasing your caster level.

You can manually adjust caster level in the Party screen, and avoid this problem by setting Chargen gestalt options in the Level Up screen to generate a cleric 1//Inquisitor 1 correctly
