### ISSUE TITLE
Feature Selection: Exotic Weapon name unreadable

### ISSUE THREAD

**Issue by Dark0Zero** [cabarius/ToyBox#513]
**Describe the bug**
I attempted to add an exotic weapon proficiency to a character only to find that I couldn't read the names of the feats.

**To Reproduce**
Should just need to load up the game and look at it. I've attached, hopefully, a screenshot to demonstrate the problem.

**Expected behavior**
I didn't expect the selection behavior, initially was a nice detail, just a list of exotic weapon feats. When It popped up I expected that it would autoscroll or adjust to my screen size to let me view it. 

**Screenshots**
![20211026215110_1](https://user-images.githubusercontent.com/90563598/138987326-6d1781c8-cbfd-4102-8394-5f110d0958f6.jpg)

**Version Info:**
 - ToyBox Version: 1.4.5
 - OS: Win10
 - Version: 1.0.9c

**Additional Information**
I'm running on a screen size of 1920x1080 if that helps.

**Comment by cabarius** [comment]
this should be fixed in latest 
![image](https://user-images.githubusercontent.com/331144/139796971-b171257d-ccc3-4bc5-9161-ab0d59d7b530.png)
