### ISSUE TITLE
Gestalt class doesnt work on respect

### ISSUE THREAD

**Issue by Cairnos** [cabarius/ToyBox#522]
Hello, i might have a bug during character creation (after using respect from your mod from party menu).

i have a Gestalt class selected in the level-up menu => char gen (magus sword saint for our exemple).
When creating my character (monk as basic class) i can select all feats and spells from both class.
However at the end after selecting the Name and Birth and choosing continue, every option and choice from the magus (the gestalt class) disapear and after the creation, i only have my monk class.

When Lvling to lvl 2, when i select Magus as the gestalt it now works properly at this point.

Dunno if intended or not and it's not game breaking, just losing 1 free lvl of your gestalt class.

Thanks for your hard work !
Toy box => ToyBox for WoTR Mod-8-1-4-6-1635366328
WOTR => 1.1.0k

**Comment by LilyEvilDM** [comment]
Having a similar issue with respeccing Seelah to a gestallt. with some main classes it seems to not allow any gestallt ones to be added, others do appear to be noticed by the respec but then are very buggy, missing features and reverting back to the main class upon finish. As with Cairnos, Gestallting does work for lv 2, stopping me from having multiple classes as the same level as my main class.
Using the newest version of:
Toybox from Nexus
Respec from github
Visual adjustments from github
