### ISSUE TITLE
0/0 mods loaded in 1.1.0k

### ISSUE THREAD

**Issue by SuneYoko** [cabarius/ToyBox#524]
Initialize engine version: 2019.4.26f1 (e0392c6b2363)
[Subsystems] Discovering subsystems at path J:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 3060 (ID=0x2504)
    Vendor:   
    VRAM:     12143 MB
    Driver:   30.0.14.7141
Begin MonoManager ReloadAssembly

[Manager] Injection...
[Manager] Initialize.
[Manager] Version: 0.23.4.0.
[Manager] OS: Microsoft Windows NT 10.0.19042.0 AMD64.
[Manager] Net Framework: 4.0.30319.42000.
[Manager] Unity Engine: 2019.4.261.
[Manager] Game: Pathfinder: Wrath of the Righteous.
[Manager] Mods path: J:\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Mods.
Fallback handler could not load library J:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/Mono/data-0000021B5B203020.dll
Fallback handler could not load library J:/SteamLibrary/steamapps/common/Pathfinder Second Adventure/Wrath_Data/Mono/data-0000021B5B5E2AC0.dll
[Manager] Injection successful.
- Completed reload, in  0.542 seconds
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.586500 ms
[Manager] Start parsing game version.
[Manager] Found game version string: '1.1.0k'.
[Manager] Game version detected as '1.1.0'.
[Manager] Parsing mods.
[Manager] FINISH. SUCCESSFUL LOADED 0/0 MODS.

[Manager] Spawning.
[MonoSingleton] There is no object of type Kingmaker.Utility.CoroutineRunner. Creating new.
[MonoSingleton] There is no object of type Kingmaker.Settings.Graphics.ApplicationFocusObserver. Creating new.
Cannot Prepare a disabled VideoPlayer 
(Filename:  Line: 315)

[Manager] Checking updates.
The referenced script on this Behaviour (Game Object 'Male_BaseSkeletonGeneric_HalfOrc') is missing! 
(Filename:  Line: 334)

Kingmaker.Localization.SharedStringAsset must be instantiated using the ScriptableObject.CreateInstance method instead of new SharedStringAsset. 
(Filename:  Line: 683)

Kingmaker.Localization.SharedStringAsset must be instantiated using the ScriptableObject.CreateInstance method instead of new SharedStringAsset. 
(Filename:  Line: 683)

Kingmaker.Localization.SharedStringAsset must be instantiated using the ScriptableObject.CreateInstance method instead of new SharedStringAsset. 
(Filename:  Line: 683)

Kingmaker.Localization.SharedStringAsset must be instantiated using the ScriptableObject.CreateInstance method instead of new SharedStringAsset. 
(Filename:  Line: 683)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object 'UnityThreadHolder') is missing! 
(Filename:  Line: 334)

Received stats and achievements from Steam
Unloading 6 Unused Serialized files (Serialized files now loaded: 226)

Unloading 14750 unused Assets to reduce memory usage. Loaded Objects now: 174904.
Total: 284.912500 ms (FindLiveObjects: 7.877900 ms CreateObjectMapping: 11.637500 ms MarkObjects: 259.142500 ms  DeleteObjects: 6.254200 ms)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename:  Line: 334)

WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
The loaded level has a different lightmaps mode than the current one. Current: Non-Directional. Loaded: Directional. Will use: Non-Directional. 
(Filename:  Line: 276)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at Kingmaker.Visual.Particles.FxAoeSpawner.SpawnFxOnEntry (Kingmaker.Visual.Particles.FxAoeSpawner+Entry entry) [0x00017] in <d172f0be739547f595586c675ace98bb>:0 
  at Kingmaker.Visual.Particles.FxAoeSpawner.OnEnable () [0x000d3] in <d172f0be739547f595586c675ace98bb>:0 
 
(Filename: <d172f0be739547f595586c675ace98bb> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at Kingmaker.Visual.Particles.FxAoeSpawner.SpawnFxOnEntry (Kingmaker.Visual.Particles.FxAoeSpawner+Entry entry) [0x00017] in <d172f0be739547f595586c675ace98bb>:0 
  at Kingmaker.Visual.Particles.FxAoeSpawner.OnEnable () [0x000d3] in <d172f0be739547f595586c675ace98bb>:0 
 
(Filename: <d172f0be739547f595586c675ace98bb> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at Kingmaker.Visual.Particles.FxAoeSpawner.SpawnFxOnEntry (Kingmaker.Visual.Particles.FxAoeSpawner+Entry entry) [0x00017] in <d172f0be739547f595586c675ace98bb>:0 
  at Kingmaker.Visual.Particles.FxAoeSpawner.OnEnable () [0x000d3] in <d172f0be739547f595586c675ace98bb>:0 
 
(Filename: <d172f0be739547f595586c675ace98bb> Line: 0)

NullReferenceException: Object reference not set to an instance of an object
  at Kingmaker.Visual.Particles.FxAoeSpawner.SpawnFxOnEntry (Kingmaker.Visual.Particles.FxAoeSpawner+Entry entry) [0x00017] in <d172f0be739547f595586c675ace98bb>:0 
  at Kingmaker.Visual.Particles.FxAoeSpawner.OnEnable () [0x000d3] in <d172f0be739547f595586c675ace98bb>:0 
 
(Filename: <d172f0be739547f595586c675ace98bb> Line: 0)

**Comment by cabarius** [comment]
This looks like nothing to do with ToyBox and everything to do with some config issue.  Please come find us on the WoTr discord https://discord.gg/F9Tjzg99 and ask for help on #mod-user-general
