### ISSUE TITLE
Feature request : No enemy AoOs, Single target full restore.

### ISSUE THREAD

**Issue by movetogitgudplease** [cabarius/ToyBox#527]
**Is your feature request related to a problem? Please describe.**
This game is absolutely garbage and I regret paying for it. The absence of a grid and the charge bug continue to plague me even into the latest patch despite everyone falsely claiming it is fixed, Often my main PC will charge an enemy on unfair with pounce, and never attack, then I will mysteriously act last in the next initiative no matter what i rolled and die due to being "Flat footed" and "not using fighting defensively

I have NO earthly clue why the game operates this way, it used to be that you could use the teleporter to move your unit closer, reclick the enemy, and the attacks would resolve. I'm furious.

**Describe the solution you'd like**
Most of my use of the cheat functions in toybox come down to the lack of an undo key in the turn order. It boggles my mind that this is NOT a stock feature in the developer commands or something, because It's absolutely something they would have needed to playtest the game. Instead of going that far, I'd like forgotten functionality in bag of tricks to make a return, namely, moving your units without provoking attacks of opportunity, so I can reposition units that should not be threatened, and a single target full heal. As of the current release, I don't really get why it is not possible to heal a unit you click at.  Instead the only option seems to be to not only heal your full party and any dead units it may contain, but also fully restore their resources.
The inability to manage this problem in the game is not really your fault, but it's a glaring black void of QOL features in a game where the DM is constantly knocking over my own units and forgetting where they go. 
**Describe alternatives you've considered**
There doesn't seem to be any. Sometimes I would get around this by blowing a round with a full heal potion cheated into the belt of my allies, however, this not only ruins their turn, since unlimited actions only applies to attacks and never to movement or spells, but it straight up doesn't work if the enemy has killed my pc, thus forcing a reload for no reason, nor does it really work if my pc is surrounded or not next in the initiative order.
**Additional context**
I don't have any screen shots, but the bag of tricks single target full healing is really what I would go for. or anything in-between. Giving it the breath of life quality if necessary, and the option to bind it to a hotkey.

As an aside, you don't really have to fix this but I also noticed you're basically the only people, unfairly and unpaid, cleaning up owlcats mess, so I figured I would let you know that as is, sleeping in town automatically ensures ambushes on the road. there is a nice write up on how stealth functions in rests for ambushes in random encounters. I generally feel like the above solutions are more than enough to help deal with the problem of ambushes, but It's definitely a mistake on owl cats part to force the stealth category empty when it will be used to determine things like this. It's also ironic that in a bid to avoid random encounters by resting in town, the player will be subjected to even more randomness.

**Comment by Flat** [comment]
To summarize you are asking for ignore attacks of opportunity from enemies and a heal/rest/full-heal the current selected unit is that correct?
