### ISSUE TITLE
Kindom build modifier slider doesn't work

### ISSUE THREAD

**Issue by DeadMor0z** [cabarius/ToyBox#528]
**Describe the bug**
Slider doesn't respond in UI, edit field ignores input. If value changed in settings.xml - doesn't affect on build time.

**Version Info:**
 - ToyBox Version: 1.4.7
 - OS: Windows
 - Version 10

**Additional context**
Tried 1.4.6 - the same.

**Comment by cabarius** [comment]
there are two sliders, does the one closer to the bottom work?

**Comment by DeadMor0z** [comment]
Yes. It was me who wrote you on discord about this issue.

**Comment by cabarius** [comment]
Fixed in 1.4.8
