### ISSUE TITLE
Broken dialogs

### ISSUE THREAD

**Issue by DeadMor0z** [cabarius/ToyBox#550]
**Describe the bug**
Selecting option in dialog will produce previous response and show the same set of options

The problem line is in ToyBox\ToyBox\classes\MonkeyPatchin\BagOfPatches\Dialog.cs:72
`Mod.Log($"found {unitEntityData.CharacterName}");`
unitEntityData can be null and will throw a NullReferenceException

**Comment by cabarius** [comment]
Is this still happening in 1.4.9?

**Comment by DeadMor0z** [comment]
Problem was solved when I changed this line to `Mod.Log($"found {unitEntityData?.CharacterName}");` and passed that dialog where exceprion happened.
I see that you made similar change? so I assume this issue is oficially fixed.
