### ISSUE TITLE
Add archetypes' spellbook always result to a base class spellbook 

### ISSUE THREAD

**Issue by tassadarpaladin** [cabarius/ToyBox#559]
**Describe the bug**
When I try to add a spellbook which belongs to a archetype class to any character, it will always reult to a spellbook of base class.

i.e. If I add a Feyspeaker spellbook (a druid archetype spellbook using CHA as main attribute) to mc, the result is a normal druid book (which main attribute is WIS)  on mc

**To Reproduce**
1. In search n pick function - Class SB or Spellbooks,
2. Give character an archetype spellbook like feyspeaker, click the feyspeaker spellbook button
3. The book which turned blue is the based class of feyspeaker, a druid spellbook (GUID fc78193f68150454483a7eea8b605b71), and the spellbook function like normal druid one.
4. Remove druid spellbook, give character a level up and choose Feyspeaker class. The book u get is the Feyspeaker spellbook (GUID c8c471f1f9889e1408347d3c7987b4f1). It's a different spellbook from step 2 and 3.

It should be able to directly give a character an archetype spellbook.

**Version Info:**
 - ToyBox Version: 1.4.10

**Comment by semiliterate** [comment]
casting attribute is by class, not attached to spellbook. Feyspeaker is a regular druid spellbook plus two features, one that sets your casting stat to charisma and one that handles extra spell access.

**Comment by tassadarpaladin** [comment]
> casting attribute is by class, not attached to spellbook. Feyspeaker is a regular druid spellbook plus two features, one that sets your casting stat to charisma and one that handles extra spell access.

actually all casting attribute and other function (like casting failure) is totally based on book but not other source (even classes), no matter if it is mentioned in features. It's the same as kingmaker.

An easy way to test this: 
1. create a new character with 1 level Feyspeaker class, u will find it has" Feyspeaker spellbook" but not "Druid spellbook" in character screen and in the mod ui.

2. wipe out its all features related to feyspeaker or druid, increase character's CHA to a large number like 100. Then u will find the spell slots is increased with CHA, and if u check level 1 spell's DC，they are 56 (10+ stat modifier:45+spell level:1). 

u may even decrease the feyspeaker class level to 0, this will cause character can equip metal armor so no druid function now. The casting part will not change.

3. directly give another character a druid spellbook and the feyspeaker feature, and do the CHA thing like step 2. U will get nothing changed. And they will change if u modify the WIS not CHA.
