### ISSUE TITLE
Caster level

### ISSUE THREAD

**Issue by Naruto1135** [cabarius/ToyBox#58]
Increase Caster Level using Toy Box increase Spell Level (1-9) instead of Caster Level, hence once the final Spell level of the class (6 or 9) is reached, whether by Toy Box or natural progression, the spell leve can no longer be increased through Toy Box.

Example:
Say I have a level 7 multi-classing character who took some levels in magus, and I want to it to take up Eldritch Knight from level 8 onwards. I need to have it be able to cast Spell Level 3 Arcane Spells, in this case caster level 7, by character level 7. But I can not do so as toy box can not increase caster level beyond 6, because magus only has 6 Spell Level.

**Comment by ArcaneTrixter** [comment]
This should be resolved :)
