### ISSUE TITLE
broken in new beta, 1.2.0f can't move characters

### ISSUE THREAD

**Issue by stt1976** [cabarius/ToyBox#628]
broken in new beta 1.2.0f, can't move characters

**To Reproduce**
1. Go to 'the game and load or start a new game'
2. Click on the screen to try and move character'

**Expected behavior**
Unable to left click anywhere on the scree

Please attach your settings.xml file from the mod folder

**Version Info:**
 - ToyBox Version: 1.4.13
 - OS: windows 10

**Comment by gouldilox** [comment]
I have the same problem
