### ISSUE TITLE
Add Camera Zoom modification option

### ISSUE THREAD

**Issue by mackiewicz** [cabarius/ToyBox#63]
Pathfinder WotR, while being an excellent game so far, has the same issue the old Pathfinder had - camera being too close to the characters. In the previous game Bag of Tricks had the option to modify the min and max distance of the camera from the ground - could you please check if the same would be possible in here? I'm just starting with the game, and already some fights are getting pretty chaotic simply because you can't see enough of the surroundings.

**Comment by cabarius** [comment]
Fixed in 1.2.4
