### ISSUE TITLE
Issues with new DLC

### ISSUE THREAD

**Issue by Concudan** [cabarius/ToyBox#637]
With the DLC, game version 1.2.0aa
There are problems with character generation.
When selecting classes, the class will not expand to show the archtypes.
Cannot select a race or sex.
Often when advancing to the next screen in character generation the screen is blank, and you have to go back, then forward again.

When I uninstall Toy Box, the generation works.

Just FYI, I understand that the new DLC is what broke the system.  I appreciate all you do, and just wanted you to know what I observed.

**Comment by Telruna** [comment]
Hi! I encountered a problem with game version 1.2.0aa
Characters cannot level. A blank screen follows after I press the yellow plus for leveling 
I cannot select a class for the next level at all

Leveling works when I uninstall Toy Box. The new DLC messed it up

Thank your for this mod. It is much appreciated

**Comment by avallanch** [comment]
Same here,
cant level up once mod is off and the game restarted its back to normal.
