### ISSUE TITLE
All enemies are 1 Hit Die (v1.4.14 on Wrath1.2.0 live)

### ISSUE THREAD

**Issue by eRaz0rHead** [cabarius/ToyBox#638]
With Toybox (and only Toybox) installed, all the enemies are only 1 Hit Die.  

My character is Level 17, and Mythic 8, so enemies are usually much tougher. Removing ToyBox resets the enemies to the regular values. 
AFAIK, I didn't set any other difficulty settings inside Toybox. It was also not a problem in the previous version combination (1.4.13+Wrath pre 1.2.0)

**Comment by ArcaneTrixter** [comment]
This is no longer reproduceable unless you use the hp slider.
