### ISSUE TITLE
Lost Belt Items

### ISSUE THREAD

**Issue by Edalwulf** [cabarius/ToyBox#647]
While I have the cheat "infinite item use" active, any item that's in a characters "belt" seems to randomly disappear on load. This also happens to inventory items, especially potions, though far less often.
I don't know if it's due to my having updated the mod multiple times, or that the characters are from a buggier time of the games existence, but it's a bit of a problem.

Specifically: they will disappear, so I can't use them from the belt tab but they'll still be counted as being in my inventory, then they'll disappear from Inventory later. Say the Dwarven Tankard that lets you summon Azata, right? I had that on my MC's belt. I load in, it's gone from the belt menu on the action bar. I go into the inventory, and it's still got its icon there, but I can't move it. It's still in the special abilities tab, though.
I load in again and it's 100% gone from inventory, but it's still in the special abilities tab.

If you need more information, I'm sorry, but I don't know where to look. I haven't been fucking with anything else that at all. I turned on weightless items _after_ this started.

**Comment by zebh** [comment]
Had this happen to my MC after Areelu's lab, I lost the pipefox and some rods, specifically the skeleton finger which was unfortunate. Possibly related to #161 

game version: 2.0.6l
toybox version: 1.4.20

**Comment by ArcaneTrixter** [comment]
I appreciate you bringing this back up.
