### ISSUE TITLE
Unlocking Myhic Paths doesn't work anymore

### ISSUE THREAD

**Issue by jbwheels** [cabarius/ToyBox#651]
**Describe the bug**
When I try to unlock Mythic Paths (any), it fails, with an error code.

**To Reproduce**
1. Go to Level Up
2. Click on any button in Mythic Paths
3. See error (in attached file)

**Expected behavior**
If I remember correctly, it just registers the selection (button image change on mouse click). Or not.

**Save Files**
Attached

**Screenshots**
Attached (image of error code)

**Settings**
Attached

**Version Info:**
 - ToyBox Version: 1.4.15
 - OS: Windows
 - Version 10

**Additional context**
Please fix -- I'm not progressing Mythic levels until I can choose the ones I want.

Edit:
I could previously choose Swarm or Gold Dragon when I hit Mythic level 8. I had just devoured the vescavor queen, and I think I could choose Dragon because I had previously unlocked it. I successfully leveled a couple companions to Dragon My 8 (Angel -> Dragon and Lich -> Dragon), but when leveling to My 9, my options reverted to Angel & Lich, respectively.

Also, I boosted everyone a Mythic level much earlier in the game, so I am ahead of the story by 1 My.

[Unlock Mythic Paths error.zip](https://github.com/cabarius/ToyBox/files/8403528/Unlock.Mythic.Paths.error.zip)

**Comment by TMPhoenix** [comment]
Seems to be a change in the signature of the StartEtude function; it now has a second boolean param.

**Comment by fishmitts** [comment]
I'm running into a similar problem...  completed the initial Gray Garrison quest to get the first level of Mythics, and I'm unable to choose any of the paths on my main except for "Mythic Hero"

**Comment by highfly117** [comment]
I currently have the same issue i'm trying to test builds but can't without being able to unlock the other paths

**Comment by jbwheels** [comment]
> Seems to be a change in the signature of the StartEtude function; it now has a second boolean param. Probably just needs a recompile against the current version.

Would be nice...

**Comment by ShonZelno** [comment]
> Кажется, это изменение подписи функции StartEtude; теперь у него есть второй логический параметр. Вероятно, просто нужна перекомпиляция против текущей версии.

How can this be done?

**Comment by TMPhoenix** [comment]
The new build for 1.3.0 seems to fix this issue, so the recompile was probably enough.
