### ISSUE TITLE
Allow Achievements doesn't appear to work

### ISSUE THREAD

**Issue by Sturmsohn** [cabarius/ToyBox#659]
The 'Allow Achievements' functionality doesn't appear to be working, at least in DLC2.  I just played through the new DLC with it active and did not receive any achievements.

**To Reproduce**
1) Have mods loaded and running, including Toybox.
2) Play through long enough to reach an achievement you don't have.  Easiest to see in conversation-based achievements.
3) Perform the action or select the option to receive the achievement.

**Expected behavior**
A Steam achievement should be awarded.

**An early save file is attached**
[SturmsohnBugSaveFile.zip](https://github.com/cabarius/ToyBox/files/8547714/SturmsohnBugSaveFile.zip)

**Screenshots**
None

**Settings**
I couldn't find any 'settings.xml', but it looks like general_settings.json is what you want.
[GeneralSettingsJson.zip](https://github.com/cabarius/ToyBox/files/8547881/GeneralSettingsJson.zip)

**Version Info:**
 - ToyBox Version: 1.4.16
 - OS: Windows 10
 - Version 10.0.19044

**Additional context**
I have not yet determined if this applies to the base game.  I have a save at the Lost Chapel, and can update this once I reach Drezen - there are Mythic paths I can take that I have not yet taken and thus don't have the achievement for.

**Comment by Joesk** [comment]
I have noticed that in the DLC 3 that it is not awarding steam achievements either.
  Win 10
 Toybox 1.4.17 (beta)

**Comment by ArcaneTrixter** [comment]
Toybox's Allow Achievements only works for a specific subset of achievements within the game based on previous conversations between Narria and the developers. This is an intended limitation, and as a result, not a bug.
