### ISSUE TITLE
Mod isn't loading in UMM

### ISSUE THREAD

**Issue by wildwinds86** [cabarius/ToyBox#661]
**Describe the bug**
I've installed the Unity Mod Manager and I've installed the Toy Box mod as per the instructions in the readme file. However when I play Pathfinder and press Ctrl+F10 to access the mod manager, ToyBox isn't listed in window. ToyBox is the only mod I've got installed so there are no mods at all visible in the mod manager window.

I've verified that the ToyBox mod is in the "Pathfinder Second Adventure/Mods" folder in my steam directory.

**To Reproduce**
Install mod as per readme instructions

**Expected behavior**
Mod should appear in the UMM window when playing Pathfinder: Wrath of the Righteous

**Save Files**
To help us reproduce your issue, please attach a named *save file*
Please zip it or GitHub will not accept it.

**Screenshots**

**Settings**
There is no settings.xml in the mod folder.

**Version Info:**
 - ToyBox Version: [e.g. 1.3.4]
 - OS: Windows 11

**Additional context**
![UMM-Installer-Window](https://user-images.githubusercontent.com/87571098/166146985-8843d221-6060-47b5-9516-2c8d15dbe8eb.jpg)
![Pathfinder-UMM](https://user-images.githubusercontent.com/87571098/166147037-8056f61b-229c-4286-8e35-40175260813a.jpg)
![Windows-Explorer-View](https://user-images.githubusercontent.com/87571098/166147043-bd6b520f-a4b4-4371-b859-19dd2f2125b7.jpg)

**Comment by chryfox** [comment]
Just downloaded 1.4.17 and I am having the same issue 

![mod issue](https://user-images.githubusercontent.com/111723684/185840643-c990710c-7cdd-434f-ab18-1d684252caa2.png)
![mod issue2](https://user-images.githubusercontent.com/111723684/185840648-d43e9bc1-1e65-4b82-bd12-1fc1e0177225.png)

**Comment by ArcaneTrixter** [comment]
This appears to have been the source code rather than a release. Newest versions from nexus should be correct.
