### ISSUE TITLE
Last update caused numerous bugs

### ISSUE THREAD

**Issue by jdgen11** [cabarius/ToyBox#668]
Hello, thanks for a wonderful mod. When you have the opportunity would you please update toybox. There are a number of bugs since the update. I am guessing its Toybox that needs to be updated after reading other bug reports. Here is a list:
1) Party follows me around Drezen, to fix I have to exit city de-select party members then re-enter Drezen.
2) I get a black screen when I rest and select any party member to a task, ie... camp camouflage, scroll or potion creation etc., I can still rest but I have to reload game ( ctrl-alt-delete), luckily the rest is saved from the autosave. If i do not select any tasks then rest works normally.
3) Turn base combat is very slow, sometimes it gets stuck on enemies turn and I have to turn of turn base combat to move combat along. 
4) Items, spells do not get used when I use them, for example, I have 1 cure light wound potion and I use it I will still have 1 cure light wound potion. This happens with spells, items and abilities. 
5) Army combat is very slow, takes several minutes to go to the next person.
I very much appreciate your help and the creation of this mod.  

I'm using Toybox version 1.4.16

**Comment by ForbAvalon** [comment]
I have the same problem like 4.
All spells and abilities well not be comsumed

**Comment by jdgen11** [comment]
I think the problem is with the mod, buy material components, the creator
released a fix and it fixed all of the problems I was having.

**Comment by jdgen11** [comment]
Hello everyone, I think the fix for the last update isn't with Toybox but with Buy Material Components, the creator released a fix https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/328. This mod seems to have fixed all the problems I was having. Hope this will help everyone.
