### ISSUE TITLE
Why can I no longer download from github?  I don't see a beta 1.4 version on nexusmods

### ISSUE THREAD

**Issue by gouldilox** [cabarius/ToyBox#673]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Save Files**
To help us reproduce your issue, please attach a named *save file*
Please zip it or GitHub will not accept it.

**Screenshots**

**Settings**
Please attach your settings.xml file from the mod folder

**Version Info:**
 - ToyBox Version: [e.g. 1.3.4]

**Additional context**

**Comment by FrijDom** [comment]
The 1.3.0k+ builds work on 1.4 as long as you have all 3 dlc

**Comment by ArcaneTrixter** [comment]
This isn't a bug, the files are just only being released on Nexus now.
