### ISSUE TITLE
Text Spacing with Dialog Results with latest update of ToyBox

### ISSUE THREAD

**Issue by derrickm1** [cabarius/ToyBox#679]
When turning on the option for Dialog Results/Preview using the latest version of Toybox, the spacing between all of the responses is very wide and it only began happening after updating.
![unknown](https://user-images.githubusercontent.com/91816672/189242919-249890b9-b98a-44d5-be6c-343772343cb3.png)

**Comment by ArcaneTrixter** [comment]
Appears to be resolved by Azdie's latest change.
