### ISSUE TITLE
PC no longer story character 

### ISSUE THREAD

**Issue by CHJOE83** [cabarius/ToyBox#686]
**Describe the bug**

When assuming mythic hero 3, placing the sword banner, I noticed that Riegel has become the story character (he performs the cutscene actions, is in the flashback, performs the dialogue, etc). Also, the option to remove Riegel from the party is no longer an option, but is available for my PC.

This wouldn't be a problem if not for the inability to chose a mythic hero progression (the interface has Riegel starting mythic hero progression at lvl 1 and the other options aren't available)

Associated faults: Riegel and Camilla bothe enter new zones at character level 0 after gestalt progression. This is an easy enough error to fix,  but might be associated.

Is there a way to edit the save file to get my PC back to being the story character? 

**To Reproduce**

**Expected behavior**

**Save Files**
To help us reproduce your issue, please attach a named *save file*
Please zip it or GitHub will not accept it.

**Screenshots**

**Settings**
Please attach your settings.xml file from the mod folder

**Version Info:**
 - ToyBox Version: 1.4.17
 - OS: windows 10
 - Version 1.4

**Additional context**

**Comment by lenerdo** [comment]
Same problem.  Something about upgrading a party member sometimes elevates them to party leader.  I can't get my character back in the lead spot and it  breaks the game.

**Comment by ArcaneTrixter** [comment]
> Associated faults: Riegel and Camilla bothe enter new zones at character level 0 after gestalt progression. This is an easy enough error to fix, but might be associated.
> 
> Is there a way to edit the save file to get my PC back to being the story character?

That is the cause. There is a button to fix it labeled "Fix Incorrect Main Character" in the Quality of Life section.
