### ISSUE TITLE
Make it Possible to Skip Random Encounters during Travel

### ISSUE THREAD

**Issue by aAshkan** [cabarius/ToyBox#689]
**Is your feature request related to a problem? Please describe.**
I find it annoying to engage in random encounters as the team travels from one location to another.

**Describe the solution you'd like**
A toggle to be able to skip this or a slider that allows users to adjust the frequency of these random encounters/battles.

**Describe alternatives you've considered**
Make the party teleport immediately to the destination

**Additional context**

**Comment by ArcaneTrixter** [comment]
You should be able to do this already?

**Comment by ArcaneTrixter** [comment]
Please let me know if the current functionality is broken and I can re-open this as an issue.
