### ISSUE TITLE
Blueprints cannot be loaded

### ISSUE THREAD

**Issue by FrijDom** [cabarius/ToyBox#692]
**Describe the bug**
Upon finishing the Blueprint Loading sequence, Toybox crashes with a severe error and must be reloaded. Attempting to use Search and Pick after reloading causes another crash.

**To Reproduce**
1. Start game
2. Load save or start new game
3. Open Search'n'Pick tab
4. Wait for blueprints to load
5. Witness Error

**Expected behavior**
I expect it not to crash when attempting one of the main features of the mod.

**Save Files**
To help us reproduce your issue, please attach a named *save file*
Please zip it or GitHub will not accept it.

**Screenshots**

**Settings**
Please attach your settings.xml file from the mod folder

**Version Info:**
 - ToyBox Version: 1.4.17
 - OS: Windows
 - Version: 10
 - Game Version: 2.0.1h

**Additional context**

**Comment by ArcaneTrixter** [comment]
This is not reproduceable on the most recent version of the game/toybox.

**Comment by FrijDom** [comment]
Yes, it appears to have been fixed between when I posted this (at which time 1.4.17 was the latest version) and now.
