### ISSUE TITLE
Changing the color of mythic path visual effects

### ISSUE THREAD

**Issue by Rosterius** [cabarius/ToyBox#694]
Would it be possible to change the color of some mythic path visual effects?

For example, the poor Demon mythic path is doomed to have glowing pink eyes.
If we could adjust the color slightly and change them to red or yellow, that would be a huge improvement.

Or imagine an angel with beautiful crimson wings instead of ugly yellow ones.
This would be a truly new level of color customization...

**Comment by ArcaneTrixter** [comment]
Please look into the [Visual Adjustments 2](https://github.com/BarleyFlour/VisualAdjustments2) mod, as it does what you want and more.
