### ISSUE TITLE
Make Mystic Theurge accessable at lvl1 arcane and lvl1 divine Spell Caster please and Spell Synthesis for this class.

### ISSUE THREAD

**Issue by Raelaryn** [cabarius/ToyBox#700]
**Is your feature request related to a problem? Please describe.**
With the actuall Features of Toybox it is not really possible to Level with Mystic Theurge at lvl 1 arcane and lvl 1 divine Caster.

**Describe the solution you'd like**
Make Mystic Theurge accessable at lvl1 arcane and lvl1 divine Spell Caster please.

**Describe alternatives you've considered**

**Additional context**

**Comment by ArcaneTrixter** [comment]
Toybox doesn't modify blueprints. You should be able to use toybox to modify your caster level to qualify, and then subsequently remove the caster levels again.
