### ISSUE TITLE
New Release Available?

### ISSUE THREAD

**Issue by nokturnihs** [cabarius/ToyBox#702]
So just wondering, saw @ArcaneTrixter posted a bug fix related to the new version of 2.04J - just wondering if that was the only change needed to make it work or if we could get a release posted?

**Comment by Fullmight** [comment]
I downloaded it, built it, and it worked for me at least.

Might still have some bugs though.

**Comment by will118zs** [comment]
> I downloaded it, built it, and it worked for me at least.
> 
> Might still have some bugs though.

Do you know how to downlaod it?

**Comment by ArcaneTrixter** [comment]
I shared a pre-release in discord [here](https://discord.com/channels/645948717400064030/815735034514112512/1042103664338272256), but this is the source code here in the repo for downloading and building.
