### ISSUE TITLE
Error to initiate

### ISSUE THREAD

**Issue by GabrielAlvesSilva** [cabarius/ToyBox#704]
After the update in Pathfinder today, the MOD ToyBox stop working.

![imagem_2022-11-15_175459639](https://user-images.githubusercontent.com/54725426/202023437-2a45e4a4-d4a2-42bf-9f4c-4926da379c91.png)

**Comment by RowanL2** [comment]
not working at the moment after game update 2.0.4j

**Comment by RowanL2** [comment]
please update the version in nexusmods when it's ready for 2.0.4j
