### ISSUE TITLE
Open Area Exit Loot Window crashes ToyBox

### ISSUE THREAD

**Issue by kazzatso** [cabarius/ToyBox#712]
**Description**
Clicking on Loot -> Open Area Exit Loot Window causes a NullReferenceException that crashes ToyBox.

**To Reproduce**
1. Open ToyBox
2. Go to Loot
3. Click on Open Area Exit Loot Window

**Expected behavior**
The Area Exit loot window opens and ToyBox doesn't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/2185019/202581816-78926887-04fe-4ff1-8f85-efb9f877ecb8.png)

**Version Info:**
 - ToyBox Version: 1.4.7
 - OS: Windows 10
 - Pathfinder: Wrath of the Righteous Version: 2.0.4i

**Comment by dustech** [comment]
Hello, this issue is still here

![image](https://user-images.githubusercontent.com/12004370/206179151-b5d071cf-c818-422e-b599-d30a301e72c5.png)


I'm on a 3440x1440 screen

best regards!
