### ISSUE TITLE
Merged CL bug

### ISSUE THREAD

**Issue by golgepapaz** [cabarius/ToyBox#713]
**Describe the bug**
Hmm latest toybox reverted my merged oracle/angel  CL to 17 from 22 .possibly cause is commit  ab1b939

**To Reproduce**
Install toybox and have merged angel/oracle. Uninstalling toybox fixes the problem.

**Settings**
Please attach your settings.xml file from the mod folder

**Version Info:**
 - ToyBox Version: 1.4.19
 - OS: windows
 - Version: 2.0.4k

**Additional context**

**Comment by gerads** [comment]
I actually think it's b61647ae20c0801a38eba259e86e177284fd130d. When I turned off the uncapped caster level setting, it set the merged caster level correctly.

**Comment by ArcaneTrixter** [comment]
It absolutely was @gerads. Appreciate the bug report, and sorry for the delay.
