### ISSUE TITLE
"Death's Consonant Weapon" Enchantment on a custom Weapon dont give the AB only Damage.

### ISSUE THREAD

**Issue by Raelaryn** [cabarius/ToyBox#716]
**Describe the bug**
So i tried so add the "Death's Consonant Weapon" Enchantment on a custom Weapon but it seems it only works for the Damage and not for the AB.

If i add the Death's Consonant Weapon-Bardiche it will provide both the Damage and the AB from Intelligence.

**To Reproduce**

**Expected behavior**
Death's Consonant Weapon" Enchantment should give AB Bonus from Int.

**Save Files**
To help us reproduce your issue, please attach a named *save file*
Please zip it or GitHub will not accept it.

**Screenshots**

**Settings**
Please attach your settings.xml file from the mod folder

**Version Info:**
 - ToyBox Version: [Newest]
 - OS: [Win 10]
 - Version [Newest]

**Additional context**

**Comment by Raelaryn** [comment]
Tried to add the permanent "Arcane Accuracy" Arcana Buff to simulate the AB Bonus for "Death's Consonant Weapon" bonus to AB but this too, does nothing.
The Arcane Accuracy Buff dont work.

**Comment by ArcaneTrixter** [comment]
This isn't a toybox bug, the enchantment just doesn't do what you expect it to do. This isn't something that would be fixed in toybox since we can't do that without modifying the blueprint.
