### ISSUE TITLE
crash in search and pick after update 2.0.6k

### ISSUE THREAD

**Issue by dustech** [cabarius/ToyBox#722]
**Describe the bug**
Crash of the toolbox

![image](https://user-images.githubusercontent.com/12004370/209133952-42a2184d-fd04-4755-91cb-8ed28382de30.png)

before the 2.0.6k update it worked as intended.

**To Reproduce**
1. Go to search and pick
2. Click on  search
3. See error

**Version Info:**
 - ToyBox Version: 1.4.19

**Comment by xxxduyduy21** [comment]
same bug&error code

**Comment by dustech** [comment]
this is what happens if you try to "rest selected"

![image](https://user-images.githubusercontent.com/12004370/209168197-4cee56a8-be56-4c63-a6ed-eccd6d4a0138.png)


the rest all function is working

**Comment by ccmedavid** [comment]
I get the same error as you after 2.0.6k. Also, Infinite abilities are not working.

**Comment by ArcaneTrixter** [comment]
@ccmedavid please make a new issue for that.

**Comment by ArcaneTrixter** [comment]
I'm also unable to reproduce the arcane reservoir one.
