### ISSUE TITLE
Crash to desktop after book event, while loading dragon encounter at Artisans Tower, ACT III

### ISSUE THREAD

**Issue by Otnar** [cabarius/ToyBox#727]
**Describe the bug**

Setup: 
WOTR Enhanced, latest version  (not beta build)
ToyBox v 1.4.19
Respect Mod v 1.10.11
Windows 10

Party contains fully respecced Greybor (have tried loading save and reverting Greybor with Toybox respec, made no difference)

In ACT III doing Dragon Hunt quest, traveling towards Artisans Tower when book event occurs. Pass skill checks (set to take minimum 10 when out of combat). Game encounter begins to load, CTD's at 61%

**Expected behavior**

Game loads encounter

**Save Files**

Included, with logs

**Settings**
Please attach your settings.xml file from the mod folder

Attached

**Additional context**
[Save n logs.zip](https://github.com/cabarius/ToyBox/files/10307434/Save.n.logs.zip)

**Comment by ArcaneTrixter** [comment]
This sounds like it was an issue with game files not toybox. I'm going to close this, but let me know if it's still an issue.
