### ISSUE TITLE
Toy Box doesn't work with newest version of PF WOTR

### ISSUE THREAD

**Issue by Zajsh1** [cabarius/ToyBox#739]
**Describe the bug**
I installed the mod using Unity Mod Manager but the mod status is never registered as OK and will not show up in game. I have tried reinstalling the mod but it still won't work. I have another mod installed that works fine so the mod manager should be working right.

**Version Info:**
 - ToyBox Version: 1.4.19
 Unity Mod Manager installs this version. If there is a newer version it doesn't seem to recognize it.

**Comment by Ogremensch** [comment]
Just ran into this myself, after the recent GOG update. Tried re-installing UMM, Toybox, WOTR. Status shows OK, but I can't pull up the Toybox menu in game and it doesn't appear at the main menu.

**Comment by ArcaneTrixter** [comment]
Please verify you're using version 1.4.20 which has `
(ArcaneTrixter) Fixes for game version 2.0.6 - fix Search & Pick, Rest Selected, Make All Features Optional` which should get you working again?

**Comment by Zajsh1** [comment]
I am unclear as to where to find version 1.4.20. I have downloaded the zip folder from the master branch and that only installs version 1.4.19 with UMM. Is there a step somewhere that I am missing or am I downloading the wrong thing?

[ToyBox-master.zip](https://github.com/cabarius/ToyBox/files/10551878/ToyBox-master.zip)

This is what downloads for me from the main page.

**Comment by ArcaneTrixter** [comment]
Toybox doesn't currently offer a built version to download from github. If you're building it, it looks like it should build as 1.4.19 still. Assuming you've actually built the release and installed it, what is the error message you're getting in the log?

**Comment by Zajsh1** [comment]
The is no error message in the log. When I click to install it in UMM it says:

Unpacking 'ToyBox-1-4-19.zip' - SUCCESS.

When I check the status section of the mod in UMM it is blank and the mod will not show up when I open the game.

**Comment by ArcaneTrixter** [comment]
There currently isn't a way to download Toybox from github. Please go download and install it from https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/8

**Comment by Zajsh1** [comment]
Alright I got it to work. I remember at some point people were saying to use Github instead of Nexus Mods and I never checked into that. Thanks for the help.
