### ISSUE TITLE
Etudes Tab Not Working - Game Version 2.0.7o

### ISSUE THREAD

**Issue by kitkatthekittykat** [cabarius/ToyBox#740]
**Describe the bug**
I can't open the etudes tab at all in my game. It just shows an error message.

**To Reproduce**
1. Go to the Toybox menu in the in-game UMM display
2. Click on the Etudes Tab
3. See error (screenshot attached below)

**Expected behavior**
The etudes tab will be displayed properly.

**Save Files**
See attached

**Screenshots**
See attached

**Settings**
See attached

**Version Info:**
 - ToyBox Version:  1.4.20
 - OS: Windows 11
 - Version 22H2

**Additional context**
Happens on all save files on my machine. Have tried uninstalling & reinstalling, redownloading Toybox, starting a new game, verifying the steam game files, & nothing has solved the issue.

![Screenshot 2023-02-17 114943](https://user-images.githubusercontent.com/124601160/219714720-9b931078-3f69-49c9-b73c-53804c3770cb.png)
[Manual_724_Nexus__23_Calistril__II__4716__13_31_24.zip](https://github.com/cabarius/ToyBox/files/10769011/Manual_724_Nexus__23_Calistril__II__4716__13_31_24.zip)
[Settings.zip](https://github.com/cabarius/ToyBox/files/10769048/Settings.zip)

**Comment by ArcaneTrixter** [comment]
This is related to the Woljif Romance mod. I've actually already added a fix which will be in the next formal release of Toybox and is currently pinned as an alpha version in discord.

**Comment by kitkatthekittykat** [comment]
Thanks for letting me know, I'll take a look! I was kinda wondering if that had anything to do with it...

**Comment by ArcaneTrixter** [comment]
This should be resolved in the release that just went out!
