### ISSUE TITLE
Kineticist's Gather Power as a move action don't work

### ISSUE THREAD

**Issue by LeKopic** [cabarius/ToyBox#75]
Hi, if I am using gather power as a move action, it seems like the character always doing it as a full-round action, at least in Turn-Based mode. 
A bit more info - tested with no other mods, character - standard kineticist with earth element and extended reach.
It works fine if I use Instant Cooldown option.

**Comment by ThisIsSovereign** [comment]
I tested this as well with only ToyBox installed, it worked fine with no mods installed. In turn-based mode If I attempt to for example use Gather Power - Low as my move action, and Extended Range as my attack - the UI will properly show this but all my character will do is Gather Power and not attack that round. It may be an issue with other move actions as well, not just this one with the Kinecticist. 

Here's a save file where the main character is ready to go into combat and can perform the actions mentioned above.

[Quick_1.zip](https://github.com/cabarius/ToyBox/files/7110746/Quick_1.zip)

**Comment by Ishindri** [comment]
I can confirm I'm seeing this as well. Save below - take my PC northeast past the glowy thing to enter into a combat. Normally just clicking on an enemy should trigger the gather and then blast, install ToyBox and the blast stops firing. Don't need to make any changes or enable any of ToyBox's settings for it to start happening.

[Manual_12_Mid_Drezen.zip](https://github.com/cabarius/ToyBox/files/7115841/Manual_12_Mid_Drezen.zip)

**Comment by ssbberggren** [comment]
Hi. I can confirm that this doesn't work for Slayer's move action Studied Target as well, among other move actions (such as using potions). It skips the Standard Action for some reason.

**Comment by Tacgnol9001** [comment]
Yes, I'm getting this issue with only the achievements setting enabled in Toybox.

Very very odd one.

**Comment by Truinto** [comment]
I can confirm that this was a big issue, but I cannot reproduce it after updating to v1.2.10+. I think it's fixed.

**Comment by ArcaneTrixter** [comment]
Marking resolved for now. Please reopen if you encounter this issue in a recent version of Toybox.
