### ISSUE TITLE
Toybox not functioning at all

### ISSUE THREAD

**Issue by wolfman6amin9** [cabarius/ToyBox#753]
Regardless of the version of Unity Mod Manager, or the version of Toybox installed, Toybox just doesn't work. It shows as "Needs Restart." I am not sure what the issue is, as previously when I had the game installed, it ran without issue. I even restarted my PC just incase that was the restart that it was asking for.

**Comment by BuckAMayzing** [comment]
Can you share game logs, your `settings.xml` file, and a screenshot of the error? The log file is `AppData/LocalLow/Owlcat Games/Pathfinder Wrath Of the Righteous/Player.log`. You should copy the file immediately after you see the error, as it is overwritten every time you run the game.

Given this hasn't been more widely reported, my best guess is that either you have an uncommonly used setting turned on that is broken or there was a conflict with another mod that was introduced by either Toybox's patch or the other mod.

**Comment by ArcaneTrixter** [comment]
This is likely a version conflict: please provide your version of toybox and version of the game you're trying to use.

**Comment by theoddrod** [comment]
i'm having the same issue. game ver 2.1.0u and toybox ver 1.4.22.

**Comment by ArcaneTrixter** [comment]
You appear to have permission errors where wrath can't access any of the mod files for either toybox or bubble buffs.

**Comment by theoddrod** [comment]
just had a insight and runned the game as an administrator...

and it worked. lmao

**Comment by ArcaneTrixter** [comment]
@wolfman6amin9 if you continue to have an issue, please provide the logs as requested above.
