### ISSUE TITLE
“Fix Alignment” not working properly

### ISSUE THREAD

**Issue by Benjaminloh82** [cabarius/ToyBox#756]
**Describe the bug*

Fix Alignment is supposed to only increment on the good-evil and law-chaos axis when choices are made. Instead it stops incrementing at all and keeps the alignment “circle” in one spot.

The alignment circle should only move on the good/evil axis or the law/chaos axis when the appropriate choices are made.

**Comment by ArcaneTrixter** [comment]
This is resolved by #755 and will be fixed in next release :)
