### ISSUE TITLE
Quick slots

### ISSUE THREAD

**Issue by Darkanyon** [cabarius/ToyBox#758]
I am no longer able to put anything in the quick slots and the spells, ability's and belt items tabs no longer function. The auto assigned ability's and spells in the quick slots still function. I can't swap any spells or ability's out. I have no idea what toolbox function I may have turned on that can cause this. Is there a way to go back to the default so I can turn on the toolbox functions one by one.

**Comment by ArcaneTrixter** [comment]
Please ensure that you're using the latest version of toybox and game update. This was fixed for the DLC release.
