### ISSUE TITLE
Multiple Classes: Character Generation's Hit Point Growth(Average/Largest/Sum) use the wrong values for their calculations

### ISSUE THREAD

**Issue by DreamTourist** [cabarius/ToyBox#76]
Tried out the new Multiple Classes in a New Game's Character Creation.
The Hit Point Growth setting this time, only PrimaryClass gets the Result's Base values correct.
e.g. Alchemist(8) + Monk(10) + Kineticist(8)
PrimaryClass = 8 or 10 (depends on the Class actually selected in Character Creation)
Average = 13 (should be 8.67, so 8/9)
Largest = 15 (should be 10)
Sum = 31 (should be 26)
*excluded Ability Modifier Bonus & Favored Class Bonus, as both are accurate for all 4 settings.
*coincidently, Basic Attack Growth Pr & Saving Throw Growth seem to be accurate.

**Comment by Deltharis** [comment]
https://github.com/cabarius/ToyBox/blob/master/ToyBox/classes/MonkeyPatchin/Multiclass/StatProgression/HP.cs#L24 - this line seems to be causing it, I don't know why would current increase be divided by 2. Math seems to check out - for largest for instance, current increase is 10, so outcome is 10 + 10 - 5 = 15

**Comment by DreamTourist** [comment]
Yup, the math seems to match my results.
But why use that math at the end though?
We obviously only need the newIncrease values, currentHPIncrease just ends up adding extra HP.

**Comment by DreamTourist** [comment]
Test on ToyBox v1-2-7 (Experimental), bug got worse?
e.g. Alchemist(8) + Monk(10) + Kineticist(8)
PrimaryClass = 8 or 10 (depends on the Class actually selected in Character Creation)
Average = 18 (should be 8.67, so 8/9)
Largest = 20 (should be 10)
Sum = 36 (should be 26)

You need to change this back:
unit.Stats.GetStat(StatType.HitPoints).BaseValue += newIncrease;
To this:
unit.Stats.GetStat(StatType.HitPoints).BaseValue += newIncrease - currentHPIncrease;
Make sure not to revert using the divide by 2 for currentHPIncrease.

**Comment by DreamTourist** [comment]
Bug is still present in v1-2-8.
Same test result as in v1-2-7.

**Comment by DreamTourist** [comment]
Test on ToyBox v1-2-9-1 (Experimental), bug FIXED.
e.g. Alchemist(8) + Monk(10) + Kineticist(8)
PrimaryClass = 8 or 10 (depends on the Class actually selected in Character Creation)
Average = 8 (should be 8.67, so 8/9)
Largest = 10 (should be 10)
Sum = 26 (should be 26)
