### ISSUE TITLE
Level reset to 0

### ISSUE THREAD

**Issue by Yohsl** [cabarius/ToyBox#761]
**Describe the bug**
Using a solo gestalt character, Aasimar Angelkin, Dragonblood Shifter/Armiger Fighter. Upon gaining the first mythic path at the end of act one, and picking up the Master Shapeshifter mythic feat, once we transition to the next act, the character level is reset to 0, forever.
Even if you manually set the character level back to what it was originally, it'll reset once again whenever you transition to another map or reloading a save.
It appears to trigger once you gain the mythic rank 1/feat. 

**To Reproduce**
1. Go to save file, in the Grey Garrison, just before the final fight on act 1.
2. Click on the Wardstone, go through the dialog options. (I chose 'Cleanse renegade angels option'
3. Defeat Minagho and her demons, complete her dialog, gain the 1st rank Mythic Feat.
4. Optional, choose a mythic feat. (I chose Closer to the Abyss and Master Shapeshifter)
5. Save on a new save, and either reload that same save, or go to act 2.
6. Once loaded, you character level should be reset to 0. 

**Expected behavior**
Once the bug triggers, your character level, but not your class levels, is reset to 0. Any attempt to change this level is undone once you reload or change map area. The bug appears to be in a loop, constantly resetting you character level to 0.

**Save Files**
To help us reproduce your issue, please attach a named *save file*
Please zip it or GitHub will not accept it.
[Manual_1058_Gray_Garrison__21_Arodus__VIII__4715__05_33_32.zip](https://github.com/cabarius/ToyBox/files/11017572/Manual_1058_Gray_Garrison__21_Arodus__VIII__4715__05_33_32.zip)

**Screenshots**

**Settings**
Please attach your settings.xml file from the mod folder
[Settings.zip](https://github.com/cabarius/ToyBox/files/11017567/Settings.zip)

**Version Info:**
 - ToyBox Version: 1.4.22

 - OS: Windows 10 Pro, Build 19044.2728
 - Version: 21H2

**Additional context**
The only other mod installed is Modded Achievements, which I seriously doubt is the one causing this problem.

**Comment by ArcaneTrixter** [comment]
Please ensure that only one of your classes is marked as gestalt.

**Comment by Yohsl** [comment]
That solved the issue.
Thou for the record I thought I had only marked one class. I don't know at what point both had become marked.
The fact that they can be, and that leads to such game breaking bugs, seems like something of a design flaw to me.
In either case thank you.
