### ISSUE TITLE
Buff Duration Slider 

### ISSUE THREAD

**Issue by caloyers** [cabarius/ToyBox#788]
**Describe the bug**
Increasing Buff Duration Slider causes summon monsters to Idle 

**To Reproduce**
1. Go to: 'Bag of Tricks in Toybox'
2. Click on 'Increase the slider of Buff Duration, lets say to 10 or 9999(max)'
3. Scroll down to: 'Other Multipliers'

**Expected behavior**
Even when the buff duration should be set to 9999 when summoning monster(via spell)
monsters should attack enemies. But they only stand idle, reseting the buff duration to default (1) 
rectifies this problem.

**Save Files**
To help us reproduce your issue, please attach a named *save file*
Please zip it or GitHub will not accept it.

**Screenshots**
Screenshot taken from Steam forums with same problem.
![image](https://user-images.githubusercontent.com/73109305/228163097-1b50d060-d819-47c4-bc60-3ff9bdb03a18.png)

**Settings**
Please attach your settings.xml file from the mod folder

**Version Info:**
 - ToyBox Version: 1.4.23
 - OS: Windows 10
 - Game Version:  2.1.1g
 - 
**Additional context**

**Comment by BuckAMayzing** [comment]
Just a general thought in case another contributor gets to this before me - there may be a hidden buff that's not officially considered harmful that's applied when you summon something. I'm not yet sure how I'd go about figuring out what that is, but it's possible a hidden buff just needs to be added to the exclusion list. 🤷

I can't take a look at this at least for the next several days as I've had some other life things to deal with.

**Comment by caloyers** [comment]
Thanks for the reply, tried searching for it in exemptions but did not appear.
![image](https://user-images.githubusercontent.com/73109305/228528802-0bd32ca0-26c0-4922-87a6-86d1123e1b84.png)

**Comment by BuckAMayzing** [comment]
Gotcha. I added some filtering to those buffs because there were some categories I thought wouldn't be relevant. I'll see if it's in that list as soon as I can.

**Comment by BuckAMayzing** [comment]
Turns out there were filters. One of the buffs is hidden from the UI by default. I'm not sure why the other one is hidden (resurrection will do the same thing, apparently). I added the buffs to the default list, so they'll be included without the ability to remove them in future versions.

Here's a preview build that includes the fix. Note you'll have to copy your `settings.xml` file from the main mod into here or you will lose all of your settings.

[0ToyBox0.zip](https://github.com/cabarius/ToyBox/files/11115362/0ToyBox0.zip)

**Comment by caloyers** [comment]
Thank You sir , now its working, fantastic.
![image](https://user-images.githubusercontent.com/73109305/228971158-9764aca3-cde8-4395-83c3-af2242410f75.png)

![image](https://user-images.githubusercontent.com/73109305/228971228-71c45270-89d2-45d4-9e14-11a0521d0da6.png)

**Comment by BuckAMayzing** [comment]
@ArcaneTrixter - you should also be able to close #471 with this too. I don't believe I have permissions to do so.
