### ISSUE TITLE
oversized having no effect

### ISSUE THREAD

**Issue by mrdude217** [cabarius/ToyBox#791]
Adding oversize to weapon appears to have no effect.

**To Reproduce**
Tried adding both oversized and oversizedpenaltynegateenchant, both don't effect the item but will add oversized to description and oversize to list of modifiers. 

**Expected behavior**
expected it to increase size of weapon, ie sword going from 1d8 to 2d6

**Version Info:**
 - ToyBox Version: 1.4.23

**Additional context**
Using the spell lead blades (increase weapon size) changes damage from 2d8 to 3d8. (working as intended, as oversized effect should I believe)
Additionally changing the size of your character via size adjustment in toybox medium->gargantuan have no effect on damage.
Colossal changes it from 3d8 to 8d8.  Unsure if related.

**Comment by CasDragon** [comment]
Don't believe this was ever a Toybox issue, just an issue with how enchantments were implemented in Wrath. Regardless, it's a stale issue, and am closing.
