### ISSUE TITLE
The newest update isn't working

### ISSUE THREAD

**Issue by xOpiate** [cabarius/ToyBox#806]
**Describe the bug**
It's saying that it "needs restart" constantly, won't load. The log is spitting out memory function allocation errors when trying to load ToyBox at startup. 
It appears game update 2.1.2d is incompatible

**Version Info:**
1.4.24

**Additional context**

**Comment by CasDragon** [comment]
If you join the Discord, there's a pinned version in #mod-user-general with changes for the new update
