### ISSUE TITLE
DC Check always -99 for Myself or party

### ISSUE THREAD

**Issue by luqman0102** [cabarius/ToyBox#818]
**Is your feature request related to a problem? Please describe.**
Never a fan of dice rolls. The saves and skill checks can be annoying

**Describe the solution you'd like**
Create an option similar to "DC -99" found in Bag of Tricks for Kingmaker

**Describe alternatives you've considered**
Perhaps make it so saving throws always succeed as an option. The same goes for skill checks

**Additional context**

**Comment by CasDragon** [comment]
The `Always Roll 20` option in `Bag of Tricks` should cover this. Closing this, but if there's something they don't cover, please reopen the issue and let us know
