### ISSUE TITLE
Smite Evil Deflection Bonus Not Applying

### ISSUE THREAD

**Issue by Swills-17** [cabarius/ToyBox#838]
The Paladin Smite Evil ability does not appear to be applying the deflection bonus to AC to the Paladin against the creature to which the Smite Evil was applied. The bonus does seem to apply when the mod is disabled.

**To Reproduce**
1. Apply Smite Evil to an evil creature
2. Allow creature to hit character that applied the Smite Evil
3. Note the combat log does not include the "Smite Evil" deflection bonus to AC
4. Check the Buffs for the evil creature and note a single "Smite Evil" buff
5. Check the 'See All' while searching for "smite" for the evil creature and note that only "SmiteEvilBuff" is applied

Steps to show which buffs are applied when Toy Box is disabled:
1. Launch the game and load a save with Toy Box disabled
2. Enter combat and apply Smite Evil against an evil enemy
3. Allow the enemy to the hit the Paladin that applied the Smite Evil
4. Note the combat log includes the "Smite Evil" deflection bonus to AC
5. Check the Buffs for the evil creature and note that two "Smite Evil" buffs are applied to it
6. Check the Show All when selecting the evil enemy and searching for "smite" and note the "SmiteEvilBuff" and "SmiteEvilBuff_NoScabbard" are applied

**Expected behavior**
The Deflection bonus from Smite Evil is applied to the Paladin when attacked by the evil creature to which the Smite Evil was applied.

**Screenshots**
![Dretch Double Smite Evil](https://user-images.githubusercontent.com/130870952/232254525-5591b5cb-97cc-43f8-9ee3-8e3a5d52abfe.jpg)
![Dretch More Smite](https://user-images.githubusercontent.com/130870952/232254530-09a75bc9-a057-440f-99db-6ecad1471736.jpg)

**Settings**
[Settings.zip](https://github.com/cabarius/ToyBox/files/11240752/Settings.zip)

**Version Info:**
 - ToyBox Version: 1.4.25
 - OS: Windows 10
 - Version: 22H2

**Comment by cabarius** [comment]
Fixed in 1.4.26 which may be reversioned to 1.5.0

**Comment by cabarius** [comment]
https://github.com/cabarius/ToyBox/commit/d00c5bdb2fb8b556969312b676adf55aff8e1ca9
