### ISSUE TITLE
Favored Terrain - Abyss missing ranking button

### ISSUE THREAD

**Issue by solo16** [cabarius/ToyBox#854]
![Favored Terrain Abyss](https://user-images.githubusercontent.com/90235244/234591568-077e4018-17b7-4dee-84a7-e1fe84a3f289.jpg)
![Favored Terrain](https://user-images.githubusercontent.com/90235244/234591585-818d44fa-c180-4a87-b237-27f35cfcaf3d.jpg)

As per title under the party features tab Favored Terrain - Abyss is missing the ranking up button where all other types of terrain have.

Thank you for looking into this!

**Comment by cabarius** [comment]
Seems to work for me 
![image](https://user-images.githubusercontent.com/331144/235282956-49079b2d-7fea-4e27-8839-0e2ea5590e3e.png)
Can you try latest?

**Comment by cabarius** [comment]
There are two concepts here. Rank and level.  I need to figure out a way to express this more clearly in the UI.

**Comment by cabarius** [comment]
This looks like something in the game.  If we look at the blueprints for these two features 
![image](https://user-images.githubusercontent.com/331144/235283704-7ae6cda8-be0b-4f98-ab0a-2d14e91523f9.png)
you will see that one has max rank of 1 and the other of 4
![image](https://user-images.githubusercontent.com/331144/235283742-84113127-919b-44e5-98e7-ec5d62778a4d.png)
![image](https://user-images.githubusercontent.com/331144/235283758-971f67d5-ccf5-4162-8e2b-2ca68f73c25b.png)
So this is behaves correctly. I will improve the display of level and rank to clarify the meaning
