### ISSUE TITLE
Add in-game chatlog output for TB actions that are not readily apparent to the user

### ISSUE THREAD

**Issue by because-bot-fed** [cabarius/ToyBox#857]
**Is your feature request related to a problem? Please describe.**
Users may not always know when/if they have toggled a setting, or if pressing a button took effect: 
Murder Hobo 
Lobotomize Enemies
Reroll Perception
Set Perception 40
etc

It's possible to bump a key or forget if you had something toggled on or off, or just be unsure if pressing the button "did the thing". 

**Describe the solution you'd like**
I think a simple message in the in-game chatlog would be more than adequate to make it easily visible to users the result of actions they take with keybinds, or just provide some peace of mind that the button did indeed do what they expected.

**Describe alternatives you've considered**
Alternative is just to open TB and check to see what state something is in. Though for reroll perception and similar you'd just press it again 'just to be safe' and assume it's working as intended. 

**Additional context**
Seemed like a nice little QoL thing but not something that'd be worth investing a lot of energy into if for some reason it turned out to be a PITA :)

**Comment by cabarius** [comment]
Implemented in 1.5.0
