### ISSUE TITLE
No spiders option

### ISSUE THREAD

**Issue by valkas338** [cabarius/ToyBox#87]
The sole reason I downloaded Bag of Tricks for Kingmaker was the option to replace giant spider models with another enemy (wolves in that case). Any chance you'll be adding that feature to a future update?

**Comment by cabarius** [comment]
I think we can do this.

**Comment by cabarius** [comment]
Can you come onto our discord: https://discord.gg/yd2Gj3PT and send me a hard save file where you are near some spiders so I can test this.  My user name is Narria on that server.

**Comment by valkas338** [comment]
Sounds good - I'll need to reinstall the game, but there's one mere minutes after the opening scene - one of the downsides of being an arachnophobic fan of crpgs. And seriously, thanks for looking into this.
