### ISSUE TITLE
Inflated HP with gestalt classes with Golden Dragon 

### ISSUE THREAD

**Issue by solo16** [cabarius/ToyBox#930]
Hi,

I've been testing the HP calculation for gestalt / multiclass and found a bug which cannot be override / manually set under the party stat tab. This only happen with golden dragon feats (For testing purpose I'm not using Path of Bling mod here just ToyBox) taken which will override the base HD to d12.

Base HP at LV 1 is 13 and every class you take at level 1 it will give you full HD which is 12 and after that 7 HP/Lv
Which it will multiply by the no. of classes you have and the level of each classes.

Here is my example:
Character LV 7;
Ranger 7/ Magus 7/Rogue 7/ Paladin 7 - - - -3 classes gestalted

If my understanding of how the base HP should be calculated the base HP without bonus for such character should be like this:

(7HP/lv * 6) + 12HP @lv1 +1(favored class) = 55 base HP 

However the reality is:
(7HP/lv * 6 (first lv always full HD) * 4 (total classes taken) ) + 13 HP (Lv1) + (12 HP *3 (except the first class have favored class bonus all other classes only take FULL HD which is 12HP) = 168 + 13 + 36 = base HP 217

I captured some screenshot hope it is easier to explain the issue.

![inflated hp class](https://github.com/cabarius/ToyBox/assets/90235244/a722bc16-51be-48ec-a533-1a900c635b49)
![inflated hp](https://github.com/cabarius/ToyBox/assets/90235244/fbda6ff2-a452-433b-800b-eaefe3f83231)

So could you please kindly have a look at it ? 
If it isn't too much for asking could we have a button / toggle or something to recalculate the HP and override the original one?

Thank you so much for your time and efforts !!!

**Comment by CasDragon** [comment]
Does the HP inflation persist through reloads? Might be related to #660

**Comment by solo16** [comment]
Yes it remains inflated throughout the game.
Yup normally you could reload the save to fix it but not for golden dragon.

**Comment by solo16** [comment]
For other companions who didn't take golden dragon feats can be manually input the right amount of HP under stat tab and it will not reset to the inflated one but that's not the case for golden dragon

**Comment by FrijDom** [comment]
This may be due to a misset setting. Can you check the 'level-up' tab, down where it lists the options for the way to calculate saves, hp, bab, and skills?

**Comment by solo16** [comment]
Yes I always set it to "PrimaryClass" for HP growth.

**Comment by solo16** [comment]
The latest preview version fixed this issue THANK YOU!
