### ISSUE TITLE
BlueprintsCache Implementation

### ISSUE THREAD

**Issue by xADDBx** [cabarius/ToyBox#956]
Loading Blueprints takes quite a bit of time. Using a BlueprintsCache and just in time blueprint loading, we'd be able to skip those loading times. At the same time, we could cache things like collation to speed up that too.

Creating a custom class that stores Information (Currently a Prototype is Available under ModKit/UI/Browser/BrowserModel) which stores all the necessary information (AssetGUID to load, Name, descprition, search key, sort key to display and search, categories and tags for collation). That class will be serialized/deserialized using a fast BinarySerializer (currently planned is ZeroFormatter with [MessagePack](https://github.com/neuecc/MessagePack-CSharp) as alternative). The cache will have some additional header information stored (Language, Installed UMM mods, installed Owlmods, Version of said mods, Game Version and a Hash). When those don't match on start, we should give the option (force?) Cache invalidation and rebuild it.

We should add exceptions to mods which invalidate the cache, since some mods (like ToyBox) don't mess with Blueprints and should therefore not be the cause of an invalidation.

My only concern is how long that cache takes to build since users would need to build those themselves, we'd need to communicate somehow that Cache Building on the first start or updates will be a thing.

This feature is still in a planning stage for now

**Comment by CasDragon** [comment]
Implemented in 1.6.0  , https://github.com/xADDBx/ToyBox-Wrath/commit/a83dc3a44a6e410a9db4ca2cf72bdbaa80306979

**Comment by xADDBx** [comment]
Not directly but close enough I guess
