### ISSUE TITLE
Search'N'Pick

### ISSUE THREAD

**Issue by amrose2** [cabarius/ToyBox#978]
### Description of the bug

After blueprints load, sit at collating forever. Never received this before.

### Steps To Reproduce

Search'n'pick > wait for blueprint load > collating forever

### Expected Behavior

search'n'pick > wait for blueprint load > search stuff freely

### Toybox Version

1.5.4.c

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.1.4w

**Comment by FrijDom** [comment]
Hi! Stepping in after some testing; This is definitely an issue. I have 16 GB ram, to preface.

These logs were from subsequent tests, in which the first (GameLogFullPrev) was 5 minutes, and the second (GameLogFull) was 30. Both appear to end on almost the exact same sequence, which appears to be immediately after the loading of the last blueprint alphabetically (Sosiel_VictimCounter, BlueprintUnlockableFlag, 597ecdcfecf342c4a8c5d1d5c3fc15d5) followed by the entering and exiting of pauses as I exit the game.

[GameLogs.zip](https://github.com/cabarius/ToyBox/files/11713821/GameLogs.zip)

**Comment by FrijDom** [comment]
Yes, I am. Sorry for the late reply, got the notif on my phone and forgot to actually reply.

**Comment by amrose2** [comment]
Every time for me. It loads the blueprints as normal, once finished it says Collating... indefinitely. Eventually the game will crash. It's a new bug with the newest version, because before now I have never seen Collating before. I've got 32GB RAM, gfx 3070, and ver 2.1.4w of the game.

Sorry, where are logs stored? I will be happy to provide one. Thank you for your work and time.

**Comment by amrose2** [comment]
[GameLogFull.txt](https://github.com/cabarius/ToyBox/files/11740107/GameLogFull.txt)
[Player.log](https://github.com/cabarius/ToyBox/files/11740109/Player.log)

Looks like reinstall does the trick. I had to fully delete it ( remove from cache in modfinder as well ) and it came up fully functional.

**Comment by amrose2** [comment]
[GameLogFullPrev.txt](https://github.com/cabarius/ToyBox/files/11751914/GameLogFullPrev.txt)
[GameLogFull.txt](https://github.com/cabarius/ToyBox/files/11751915/GameLogFull.txt)
[Player.log](https://github.com/cabarius/ToyBox/files/11751917/Player.log)

Just rolled back to 1.5.1 for now. All working there at least.
