### ISSUE TITLE
Ember gestalt / multiclass leveling issue

### ISSUE THREAD

**Issue by solo16** [cabarius/ToyBox#979]
### Description of the bug

Early in the game just recruited Ember and trying to level up with multiple classes. (From Lv3 to Lv4)

For the first level of the new classes it works fine but from Lv2 ( Ember at Lv3) onward I'm not able to level up all the classes without leveling up the main class as well.

What I'm trying to do is to level up all the new classes to the same level of the main class.

However if I keep leveling up along with the main class everything is fine except instead of Lv4 for all classes it resulted in Lv6 for the main and all other classes are lv4

This issue does not happen with other character / companions ONLY Ember so far.

### Steps To Reproduce

1) Gestalt the main class
2) Uncheck one of the class from gestalt 
3) During level up screen select one of the class other than the main
4) Checked the box for all the class for level up
5) The top part of the level up screen only show the feats selection for the current selected class instead of all others
6) At the result page at the end of level up it will only show the selected class being leveled up
7) open the character sheet suddenly all other classes being reported level up as well without actually taking any feats during the leveling up 

### Expected Behavior

I expect to level up all the new class instead of one class. 

### Log Files

[GameLog.txt](https://github.com/cabarius/ToyBox/files/11715301/GameLog.txt)
[GameLogFull.txt](https://github.com/cabarius/ToyBox/files/11715302/GameLogFull.txt)
[GameLogFullPrev.txt](https://github.com/cabarius/ToyBox/files/11715303/GameLogFullPrev.txt)
[GameLogPrev.txt](https://github.com/cabarius/ToyBox/files/11715305/GameLogPrev.txt)
[Player.log](https://github.com/cabarius/ToyBox/files/11715306/Player.log)
[Player-prev.log](https://github.com/cabarius/ToyBox/files/11715307/Player-prev.log)

### Save File

[Manual_1240_Ember_level_up_issue.zip](https://github.com/cabarius/ToyBox/files/11715312/Manual_1240_Ember_level_up_issue.zip)

### Settings

[Settings.zip](https://github.com/cabarius/ToyBox/files/11715323/Settings.zip)

### Toybox Version

1.5.4c

### Operating System

Windows 10 22H2

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.1.4w

**Comment by CasDragon** [comment]
Your issue is the same as #922. Currently gestalt is broken when trying to gestalt a character below their recruit level. 

The current workaround is listed here in the [Gestalt Guide](https://github.com/cabarius/ToyBox/wiki/Gestalt-Guide#gestalt-a-companion-with-toybox-only)
